/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdmin;

import Business.Enterprise.InsuranceEnterprise;
import Business.Plan;
import Business.PlanCatalouge;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddPlanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPlanJPanel
     */
    JPanel UserProcessContainer;
    PlanCatalouge planCatalouge;
    InsuranceEnterprise insuranceEnterprise;
    public AddPlanJPanel(JPanel UserProcessContainer,PlanCatalouge planCatalouge,InsuranceEnterprise insuranceEnterprise) {
        
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.planCatalouge = planCatalouge;
        this.insuranceEnterprise = insuranceEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        planNamejTextField = new javax.swing.JTextField();
        planPricejTextField = new javax.swing.JTextField();
        addPlanjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add Plan");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 29, -1, -1));

        jLabel2.setText("Plan Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 89, -1, -1));

        jLabel3.setText("Plan Price");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 130, -1, -1));
        add(planNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 83, 91, -1));

        planPricejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planPricejTextFieldActionPerformed(evt);
            }
        });
        add(planPricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 127, 91, -1));

        addPlanjButton.setText("Add Plan");
        addPlanjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlanjButtonActionPerformed(evt);
            }
        });
        add(addPlanjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 283, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 283, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void planPricejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planPricejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planPricejTextFieldActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void addPlanjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlanjButtonActionPerformed
        // TODO add your handling code here:
        if(planNamejTextField.getText().length() == 0 ||
                planPricejTextField.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Some of the feilds are null");
         }
         else
         {
             try {
                   Integer.parseInt(planPricejTextField.getText());
                   
             
             } catch (NumberFormatException e) {
           
            JOptionPane.showMessageDialog(null, "Plan Price Must be a Numeric");
            return;
        }
        
        Plan plan = insuranceEnterprise.getPlanCatalouge().newPlan();
        plan.setPlanName(planNamejTextField.getText());
        plan.setInitialPrice(Integer.parseInt(planPricejTextField.getText()));
        plan.setInsuranceEnterprise(insuranceEnterprise);
        plan.setType("Individual");
        JOptionPane.showMessageDialog(null, "Plan Created Sucessfully");        
         }
        
    }//GEN-LAST:event_addPlanjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlanjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField planNamejTextField;
    private javax.swing.JTextField planPricejTextField;
    // End of variables declaration//GEN-END:variables
}
