/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdmin;

import Business.Plan;
import Business.PlanCatalouge;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddPlanForSmallBusinessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPlanForSmallBusinessJPanel
     */
    JPanel UserProcessContainer;
    PlanCatalouge planCatalogue;
    UserAccount userAccount;
    public AddPlanForSmallBusinessJPanel(JPanel UserProcessContainer,PlanCatalouge planCatalogue,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.planCatalogue = planCatalogue;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        planNamejTextField = new javax.swing.JTextField();
        planFeejTextField = new javax.swing.JTextField();
        coveredjTextField = new javax.swing.JTextField();
        createjButton = new javax.swing.JButton();
        baackjButton = new javax.swing.JButton();
        coveragejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        discountjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add Small Business Plans");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 36, -1, -1));

        jLabel2.setText("Plan Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 89, -1, -1));

        jLabel3.setText("Plan Fee");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 127, -1, -1));

        jLabel4.setText("No Of Persons Covered");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 165, -1, -1));

        jLabel5.setText("Coverage");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 203, -1, -1));
        add(planNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 86, 87, -1));
        add(planFeejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 124, 87, -1));
        add(coveredjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 162, 87, -1));

        createjButton.setText("Create");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });
        add(createjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        baackjButton.setText("Back >>");
        baackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baackjButtonActionPerformed(evt);
            }
        });
        add(baackjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 260, -1, -1));
        add(coveragejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 200, 87, -1));

        jLabel6.setText("Offered Discount");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 241, -1, -1));
        add(discountjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 238, 87, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void baackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baackjButtonActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_baackjButtonActionPerformed

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        // TODO add your handling code here:
        
       if(planNamejTextField.getText().length() == 0 ||
                planFeejTextField.getText().length() == 0
               || coveredjTextField.getText().length() == 0 
               || coveragejTextField.getText().length() == 0
               )
        {
            JOptionPane.showMessageDialog(null, "Some of the feilds are null");
         }
         else
         {
             try {
                   Integer.parseInt(planFeejTextField.getText());
                   
                   Integer.parseInt(coveredjTextField.getText());
                   
                   Integer.parseInt(coveragejTextField.getText());
             
             } catch (NumberFormatException e) {
           
            JOptionPane.showMessageDialog(null, "Last three feilds  Must be a Numeric");
            return;
        }
        
        Plan plan = planCatalogue.newPlan();
        plan.setFee(Integer.parseInt(planFeejTextField.getText()));
        plan.setPlanName(planNamejTextField.getText());
        plan.setNoOfPersonsCovered(Integer.parseInt(coveredjTextField.getText()));
        plan.setInsuranceEnterprise(userAccount.getInsuranceEnterprise());
        plan.setType("Small Business");
        plan.setOfferedDiscount(Integer.parseInt(discountjTextField.getText()));
        plan.setCoverage(Integer.parseInt(coveragejTextField.getText()));
        JOptionPane.showMessageDialog(null,"Plan Added");
        
    }//GEN-LAST:event_createjButtonActionPerformed
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baackjButton;
    private javax.swing.JTextField coveragejTextField;
    private javax.swing.JTextField coveredjTextField;
    private javax.swing.JButton createjButton;
    private javax.swing.JTextField discountjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField planFeejTextField;
    private javax.swing.JTextField planNamejTextField;
    // End of variables declaration//GEN-END:variables
}
