/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdmin;

import Business.Business;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Exchange.Exchange;
import Business.Markets;
import Business.Offer;
import Business.Plan;
import Business.PlanCatalouge;
import Business.UserAccount;
import Business.UserAccountDirectory;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class InsuranceAdminWRJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceAdminWRJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Business business;
    UserAccountDirectory userAccountDirectory;
    UserAccount adminUserAccount;
    Markets markets;
    EmployeeDirectory employeeDirectory;
    InsuranceEnterprise insuranceEnterprise;
    PlanCatalouge planCatalouge;
    public InsuranceAdminWRJPanel(JPanel UserProcessContainer,UserAccount userAccount,PlanCatalouge planCatalouge) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.planCatalouge = planCatalouge;
        employeeDirectory = userAccount.getInsuranceEnterprise().getEmployeeDirectory();
        //business = Business.getInstanceOfBusiness();
       // userAccountDirectory = business.getExchangeEnterprise().getUserAccountDirectory();
      //  markets = business.getMarkets();
        insuranceEnterprise = userAccount.getInsuranceEnterprise();
       
        wrTypejComboBox.removeAllItems();
        wrTypejComboBox.addItem("Plan");
        wrTypejComboBox.addItem("Offer");
        exchangejComboBox.removeAllItems();
//        for(Enterprise enterprise:business.getEnterpriseDirectory().getEnterpriseDirectory())
//        {
//            if(enterprise.getEnterpriseName().equals("Exchange"))
//            {
//                exchangejComboBox.addItem(enterprise);
//            }
//        }
        for(Exchange exchangeEnterprise : userAccount.getInsuranceEnterprise().getExchangeEnterprises())
        {
            exchangejComboBox.addItem(exchangeEnterprise);
        }
        
        planRefresh();
//        for(Plan p :userAccount.getInsuranceEnterprise().getPlanCatalouge().getPlanCatalouge())
//        {
//            if(p.getType().equals("Small Business"))
//            {
//                employeejComboBox.addItem(p);
//            }
//            
//        }
        
        wrTypejComboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                try {
                    String selectedWRtype = (String)wrTypejComboBox.getSelectedItem();
                    if (e.getStateChange() == ItemEvent.SELECTED) {
                        if(selectedWRtype.equals("Offer"))
                        {
                        employeejComboBox.removeAllItems();
                        offerjComboBox.removeAllItems();
                        
                            for(Offer o: insuranceEnterprise.getOffers().getOffers())
                              {
                                
                               offerjComboBox.addItem(o);
                                
                              }
                        
                        }
                        else if(selectedWRtype.equals("Plan"))
                                {
                                    offerjComboBox.removeAllItems();
                                    planRefresh();
                                    
                                }
                    }
                    //throw new UnsupportedOperationException("Not supported yet.");
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        } );
        
    }
    public void planRefresh()
    {
        employeejComboBox.removeAllItems();
        for(Plan p : planCatalouge.getPlanCatalouge())
        {
            if(p.getType().equals("Small Business"))
            {
                employeejComboBox.addItem(p);
            }
            
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        offerjComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        remarksjTextField = new javax.swing.JTextField();
        sentForApprovaljButton = new javax.swing.JButton();
        viewOtherRequestsjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        employeejComboBox = new javax.swing.JComboBox();
        wrTypejComboBox = new javax.swing.JComboBox();
        backjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        exchangejComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Insurance Admin Work Requests");

        jLabel2.setText("Work Request Type");

        jLabel3.setText("Select Your Offer for Approval ");

        jLabel4.setText("Remarks");

        sentForApprovaljButton.setText("Sent for Approval");
        sentForApprovaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentForApprovaljButtonActionPerformed(evt);
            }
        });

        viewOtherRequestsjButton.setText("View Other Requests");
        viewOtherRequestsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOtherRequestsjButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Select Plan  For Approval");

        wrTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrTypejComboBoxActionPerformed(evt);
            }
        });

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Exchange Enterprise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)
                        .addGap(134, 134, 134)
                        .addComponent(wrTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3)
                        .addGap(80, 80, 80)
                        .addComponent(offerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel5)
                        .addGap(109, 109, 109)
                        .addComponent(employeejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel6)
                        .addGap(130, 130, 130)
                        .addComponent(exchangejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel4)
                        .addGap(188, 188, 188)
                        .addComponent(remarksjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(backjButton)
                        .addGap(31, 31, 31)
                        .addComponent(viewOtherRequestsjButton)
                        .addGap(55, 55, 55)
                        .addComponent(sentForApprovaljButton)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(wrTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(offerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(employeejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(exchangejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(remarksjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewOtherRequestsjButton)
                        .addComponent(sentForApprovaljButton)))
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sentForApprovaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentForApprovaljButtonActionPerformed
        // TODO add your handling code here:
        if(userAccount.getInsuranceEnterprise().getExchangeEnterprises().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "You are not registered with any of the exchanges");
                        return;
        }
        String selectedWRtype = (String)wrTypejComboBox.getSelectedItem();
        Exchange selectedExchange = (Exchange)exchangejComboBox.getSelectedItem();
        Plan selectedPlan = (Plan)employeejComboBox.getSelectedItem();
        Offer selectedOffer = (Offer) offerjComboBox.getSelectedItem();
        if(selectedWRtype.equals("Plan"))
                    {
            for(WorkRequest wR2 : selectedExchange.getReceivingQueue().getWorkQueue())
            {
                if(wR2.getType().equals("Plan") &&(wR2.getStatus().equals("Approved")||wR2.getStatus().equals("InProgress")))
                {
                    if(wR2.getPlan().equals(selectedPlan))
                    {
                        JOptionPane.showMessageDialog(null, "Plan alreeady sent to exchange for approval");
                        return;
            }
        }
            }
                    }
                
        if(selectedWRtype.equals("Offer"))
                    {
            for(WorkRequest wR3 : selectedExchange.getReceivingQueue().getWorkQueue())
            {
                if(wR3.getType().equals("Offer")&&(wR3.getStatus().equals("Approved") ||wR3.getStatus().equals("InProgress"))&&wR3.getOffer().getStatus().equals("Approved") )
                {
                    if(wR3.getOffer().equals(selectedOffer))
                    {
                        JOptionPane.showMessageDialog(null, "Offer alreeady sent to exchange for approval");
                        return;
            }
        }
            }
                    }
        
        WorkRequest workRequest = userAccount.getRole().getWorkArea().getWorkQueue().newWorkRequest();
        workRequest.setType(selectedWRtype);
        workRequest.setSender(userAccount);
        workRequest.setStatus("InProgress");
        
        if(selectedWRtype.equals("Plan"))
        {
            
            workRequest.setPlan(selectedPlan);
        }
        if(selectedWRtype.equals("Offer"))
        {
            
            workRequest.setOffer(selectedOffer);
        }
        workRequest.setInsuranceEnterprise(userAccount.getInsuranceEnterprise());
         
        selectedExchange.getReceivingQueue().getWorkQueue().add(workRequest);
//        for(UserAccount ua: userAccountDirectory.getUserDirectory())
//        {
//            if(ua.getPerson().getFirstName().equals("Bharath"))
//            {
//                ua.getRole().getWorkArea().getWorkQueue().getWorkQueue().add(workRequest);
//            }
//        }
        JOptionPane.showMessageDialog(null, "Work Request Sent to Exchange");
    }//GEN-LAST:event_sentForApprovaljButtonActionPerformed
                    
    private void wrTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wrTypejComboBoxActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void viewOtherRequestsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOtherRequestsjButtonActionPerformed
        // TODO add your handling code here:
        ViewOtherRequestsJPanel  viewOtherRequestsJPanel  = new  ViewOtherRequestsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("viewOtherRequests",viewOtherRequestsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_viewOtherRequestsjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox employeejComboBox;
    private javax.swing.JComboBox exchangejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox offerjComboBox;
    private javax.swing.JTextField remarksjTextField;
    private javax.swing.JButton sentForApprovaljButton;
    private javax.swing.JButton viewOtherRequestsjButton;
    private javax.swing.JComboBox wrTypejComboBox;
    // End of variables declaration//GEN-END:variables
}
