/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.PlanCatalouge;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class InsuranceAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceAdminWorkAreaJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Business business;
    PlanCatalouge planCatalouge;
    InsuranceEnterprise insuranceEnterprise;
    PlanCatalouge planCatalogue;
    
    public InsuranceAdminWorkAreaJPanel(JPanel UserProcessContainer,UserAccount userAccount,Enterprise e,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
       // business = Business.getInstanceOfBusiness();
       // planCatalouge = userAccount.getInsuranceEnterprise().getPlanCatalouge();
        insuranceEnterprise = userAccount.getInsuranceEnterprise();
        planCatalogue = insuranceEnterprise.getPlanCatalouge();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addOffersjButton = new javax.swing.JButton();
        createPlanjButton = new javax.swing.JButton();
        viewandsendWRjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        createSmallBusinessjButton = new javax.swing.JButton();
        managejButton = new javax.swing.JButton();
        manageUserAccountsjButton = new javax.swing.JButton();
        updateOffersjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Insurance Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        addOffersjButton.setText("Add Offers");
        addOffersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOffersjButtonActionPerformed(evt);
            }
        });
        add(addOffersjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 145, 210, -1));

        createPlanjButton.setText("Create Plan");
        createPlanjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlanjButtonActionPerformed(evt);
            }
        });
        add(createPlanjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 198, 210, -1));

        viewandsendWRjButton.setText("View and Send Work Requests");
        viewandsendWRjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewandsendWRjButtonActionPerformed(evt);
            }
        });
        add(viewandsendWRjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 256, 210, -1));

        jButton1.setText("Register to Exchange Enterprise");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 145, 200, -1));

        createSmallBusinessjButton.setText("Create Small Business Plans");
        createSmallBusinessjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSmallBusinessjButtonActionPerformed(evt);
            }
        });
        add(createSmallBusinessjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 312, 210, -1));

        managejButton.setText("Manage Staff");
        managejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managejButtonActionPerformed(evt);
            }
        });
        add(managejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 198, 200, -1));

        manageUserAccountsjButton.setText("Manage UserAccounts");
        manageUserAccountsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountsjButtonActionPerformed(evt);
            }
        });
        add(manageUserAccountsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 256, 200, -1));

        updateOffersjButton.setText("Update Offers");
        updateOffersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOffersjButtonActionPerformed(evt);
            }
        });
        add(updateOffersjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 312, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createPlanjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlanjButtonActionPerformed
        // TODO add your handling code here:
         AddPlanJPanel addPlanJPanel  = new AddPlanJPanel(UserProcessContainer,planCatalouge,insuranceEnterprise);
        UserProcessContainer.add("addPlan",addPlanJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_createPlanjButtonActionPerformed

    private void addOffersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOffersjButtonActionPerformed
        // TODO add your handling code here:
        AddOffersJPanel addOffersJPanel  = new AddOffersJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("addOffers",addOffersJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_addOffersjButtonActionPerformed

    private void viewandsendWRjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewandsendWRjButtonActionPerformed
        // TODO add your handling code here:
        InsuranceAdminWRJPanel insuranceAdminWRJPanel  = new InsuranceAdminWRJPanel(UserProcessContainer,userAccount,planCatalogue);
        UserProcessContainer.add("ViewWR",insuranceAdminWRJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_viewandsendWRjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegistertoExchangePanel registertoExchangePanel  = new RegistertoExchangePanel(UserProcessContainer,userAccount,business);
        UserProcessContainer.add("RegisterToExchange",registertoExchangePanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createSmallBusinessjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSmallBusinessjButtonActionPerformed
        // TODO add your handling code here:
        AddPlanForSmallBusinessJPanel addPlanForSmallBusinessJPanel  = new AddPlanForSmallBusinessJPanel(UserProcessContainer,planCatalogue,userAccount);
        UserProcessContainer.add("addSmallBusinessPlans",addPlanForSmallBusinessJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_createSmallBusinessjButtonActionPerformed

    private void managejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managejButtonActionPerformed
        // TODO add your handling code here:
        AddCompanyEmployeeJPanel addCompanyEmployeeJPanel  = new AddCompanyEmployeeJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("addCompanyEmployee",addCompanyEmployeeJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_managejButtonActionPerformed

    private void manageUserAccountsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountsjButtonActionPerformed
        // TODO add your handling code here:
        ManageCompanyUserAccountsJPanel manageCompanyUserAccountsJPanel  = new ManageCompanyUserAccountsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("addCompanyUserAccount",manageCompanyUserAccountsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_manageUserAccountsjButtonActionPerformed

    private void updateOffersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOffersjButtonActionPerformed
        // TODO add your handling code here:
        ManageOffersJPanel manageOffersJPanel  = new ManageOffersJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("updateOffers",manageOffersJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_updateOffersjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOffersjButton;
    private javax.swing.JButton createPlanjButton;
    private javax.swing.JButton createSmallBusinessjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageUserAccountsjButton;
    private javax.swing.JButton managejButton;
    private javax.swing.JButton updateOffersjButton;
    private javax.swing.JButton viewandsendWRjButton;
    // End of variables declaration//GEN-END:variables
}
