/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Exchange.Exchange;
import Business.UserAccount;
import Business.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class RegistertoExchangePanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistertoExchangePanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Business business;
    public RegistertoExchangePanel(JPanel UserProcessContainer,UserAccount userAccount,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
       // business = Business.getInstanceOfBusiness();
        exchangejComboBox.removeAllItems();
       
        for(Enterprise enterprise:business.getEnterpriseDirectory().getEnterpriseDirectory())
        {
            if(enterprise.getEnterpriseName().equals("Exchange"))
            {
                exchangejComboBox.addItem(enterprise);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exchangejComboBox = new javax.swing.JComboBox();
        registerjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Register to Exchange");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 29, -1, -1));

        jLabel2.setText("Select Your Exchange");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 81, -1, -1));

        add(exchangejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 78, 111, -1));

        registerjButton.setText("Register");
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });
        add(registerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 141, -1, -1));

        jButton1.setText("Back >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 205, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        // TODO add your handling code here:
        
        Exchange selectedExchange = (Exchange)exchangejComboBox.getSelectedItem();
        
                    
            for(WorkRequest wR2 : selectedExchange.getReceivingQueue().getWorkQueue())
            {
                if(wR2.getType().equals("Issuer Registartion") &&(wR2.getStatus().equals("Approved")||wR2.getStatus().equals("Not Yet Registered")))
                {
                    if(wR2.getInsuranceEnterprise().equals(userAccount.getInsuranceEnterprise()))
                    {
                        JOptionPane.showMessageDialog(null, "Already in approval stage");
                        return;
            }
        }
            }
                    
        WorkRequest wR = selectedExchange.getReceivingQueue().newWorkRequest();
        wR.setType("Issuer Registartion");
        wR.setStatus("Not Yet Registered");
        wR.setSender(userAccount);
        wR.setInsuranceEnterprise(userAccount.getInsuranceEnterprise());
        userAccount.getRole().getWorkArea().getWorkQueue().getWorkQueue().add(wR);
        JOptionPane.showMessageDialog(null, "Sent For Registration");
        
    }//GEN-LAST:event_registerjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox exchangejComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registerjButton;
    // End of variables declaration//GEN-END:variables
}
