/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdmin;

import Business.UserAccount;
import Business.WorkQueue;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ViewOtherRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOtherRequestsJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    
    public ViewOtherRequestsJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        Refresh();
        
    }
    public void Refresh()
    {
        WorkQueue workQueue = userAccount.getRole().getWorkArea().getWorkQueue();
        ArrayList<WorkRequest> workQueueList = workQueue.getWorkQueue();
        int rowCount = viewORjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)viewORjTable.getModel()).removeRow(i);
       }
                        
        for(WorkRequest wR : workQueueList)
        {
                       
          
            Object row[] = new Object[4];
            
            row[0] = wR.getType();
            if(wR.getType().equals("Offer"))
            {
            row[1] = wR.getOffer();
            }
            else if (wR.getType().equals("Plan"))
            {
              row[1] = wR.getPlan(); 
            }
            else
            {
                row[1] = wR.getInsuranceEnterprise();
            }
            row[2] = wR;
            row[3] = "Exchange";
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)viewORjTable.getModel();
                    defTableModel.addRow(row);
           }     
            
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewORjTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewORjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Type", "Content", "Status", "EnterpriseType"
            }
        ));
        jScrollPane1.setViewportView(viewORjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 75, -1, 84));

        jButton1.setText("Back >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 324, -1, -1));

        jLabel1.setText("View Other Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 19, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewORjTable;
    // End of variables declaration//GEN-END:variables
}
