/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AutoDebitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AutoDebitJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    boolean indCheck = false;
    public AutoDebitJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cardNumberjTextField1 = new javax.swing.JTextField();
        expDatejTextField2 = new javax.swing.JTextField();
        CvvjTextField = new javax.swing.JTextField();
        enablejButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(102, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Auto Debit");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 27, -1, -1));

        jLabel2.setText("Card Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 62, -1, -1));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 183, -1, -1));

        jLabel3.setText("Exp Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 106, -1, -1));

        jLabel5.setText("CVV Number");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 158, -1, -1));

        jButton1.setText("Enter ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 292, -1, -1));

        jButton2.setText("Back >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 292, -1, -1));
        add(cardNumberjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 59, 76, -1));
        add(expDatejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 103, 76, -1));
        add(CvvjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 152, 76, -1));

        enablejButton.setText("ENable Auto Debit");
        enablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enablejButtonActionPerformed(evt);
            }
        });
        add(enablejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 292, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(cardNumberjTextField1.getText().length() == 0 || cardNumberjTextField1.getText().length() != 16
              || expDatejTextField2.getText().length() == 0
               || CvvjTextField.getText().length() == 0
               )
       {
           JOptionPane.showMessageDialog(null, "Some of the feilds are null or card number length is not equal to 16");
       }
       else
    {
        try {
                   
                   Integer.parseInt(CvvjTextField.getText());
             
             } catch (NumberFormatException e) {
           
            JOptionPane.showMessageDialog(null, "Card No and Cvv Must be a Numeric");
            return;
        }
        userAccount.getCustomer().getAutoDebit().setCardNumber((cardNumberjTextField1.getText()));
        userAccount.getCustomer().getAutoDebit().setCvv(Integer.parseInt(CvvjTextField.getText()));
        userAccount.getCustomer().getAutoDebit().setExpDate(expDatejTextField2.getText());
        JOptionPane.showMessageDialog(null, "Card Information Updated");
        indCheck = true;
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void enablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enablejButtonActionPerformed
        // TODO add your handling code here:
        if(indCheck == false)
        {
            JOptionPane.showMessageDialog(null, "Must enter Card Details");
            return;
        }
         userAccount.getCustomer().getAutoDebit().setAutoDebitStatus(true);
            
            JOptionPane.showMessageDialog(null, "AutoDebitEnabled");
    }//GEN-LAST:event_enablejButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CvvjTextField;
    private javax.swing.JTextField cardNumberjTextField1;
    private javax.swing.JButton enablejButton;
    private javax.swing.JTextField expDatejTextField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
