/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Family.Dependents;
import Business.MovingText.MovingText;
import Business.UserAccount;
import UserInterface.CustomerRegistration.AddFamilyJPanel;
import UserInterface.CustomerRegistration.AddHealthRecordJPanel;
import java.awt.CardLayout;
import java.awt.Label;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    Dependents dependents;
    MovingText movingText;
    Label label;
    String text = "uu";
    Business business;
    public CustomerWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        dependents = userAccount.getPerson().getDependents();
        
        
       
       
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jLabel1 = new javax.swing.JLabel();
        giveYourHealthRecordjButton = new javax.swing.JButton();
        viewYourOffersjButton = new javax.swing.JButton();
        viewYourFinancialAccountjButton = new javax.swing.JButton();
        AlertsjButton = new javax.swing.JButton();
        payYourPremiumjButton = new javax.swing.JButton();
        addYourFamilyjButton = new javax.swing.JButton();
        viewTransactionsjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        alertsjButton = new javax.swing.JButton();
        viewPaymentPlansjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Customer Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 51, -1, -1));

        giveYourHealthRecordjButton.setText("Give Your Health Record");
        giveYourHealthRecordjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveYourHealthRecordjButtonActionPerformed(evt);
            }
        });
        add(giveYourHealthRecordjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 105, 160, -1));

        viewYourOffersjButton.setText("View Your Offers");
        viewYourOffersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewYourOffersjButtonActionPerformed(evt);
            }
        });
        add(viewYourOffersjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 178, 160, -1));

        viewYourFinancialAccountjButton.setText("View Your Financial Account");
        viewYourFinancialAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewYourFinancialAccountjButtonActionPerformed(evt);
            }
        });
        add(viewYourFinancialAccountjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 105, 170, -1));

        AlertsjButton.setText("Add Bank Account");
        AlertsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlertsjButtonActionPerformed(evt);
            }
        });
        add(AlertsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 178, 170, -1));

        payYourPremiumjButton.setText("Pay Your Premium");
        payYourPremiumjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payYourPremiumjButtonActionPerformed(evt);
            }
        });
        add(payYourPremiumjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 255, 160, -1));

        addYourFamilyjButton.setText("Add Your Family");
        addYourFamilyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addYourFamilyjButtonActionPerformed(evt);
            }
        });
        add(addYourFamilyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 255, 170, -1));

        viewTransactionsjButton.setText("View Transactions");
        viewTransactionsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionsjButtonActionPerformed(evt);
            }
        });
        add(viewTransactionsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 326, 160, -1));

        jButton1.setText("Update Marital Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 326, 170, -1));

        alertsjButton.setText("Alerts");
        alertsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertsjButtonActionPerformed(evt);
            }
        });
        add(alertsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 170, -1));

        viewPaymentPlansjButton.setText("View Payment Plans");
        viewPaymentPlansjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentPlansjButtonActionPerformed(evt);
            }
        });
        add(viewPaymentPlansjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 397, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewYourOffersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewYourOffersjButtonActionPerformed
        // TODO add your handling code here:
        ViewYourOffersJPanel viewYourOffersJPanel  = new ViewYourOffersJPanel(userProcessContainer,userAccount,business);
        userProcessContainer.add("viewyouroffers",viewYourOffersJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewYourOffersjButtonActionPerformed

    private void viewYourFinancialAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewYourFinancialAccountjButtonActionPerformed
        // TODO add your handling code here:
        CustomerFinancialAccountJPanel customerFinancialAccountJPanel  = new CustomerFinancialAccountJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("Customer Financial Account",customerFinancialAccountJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewYourFinancialAccountjButtonActionPerformed

    private void payYourPremiumjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payYourPremiumjButtonActionPerformed
        // TODO add your handling code here:
        if(userAccount.getCustomer().getAutoDebit().getCardNumber() == null)
        {
            JOptionPane.showMessageDialog(null, "Must enter Card Details");
            return;
        }
        PayYourMonthlyPremiumJPanel payYourMonthlyPremiumJPanel  = new PayYourMonthlyPremiumJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("Payment",payYourMonthlyPremiumJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_payYourPremiumjButtonActionPerformed

    private void addYourFamilyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addYourFamilyjButtonActionPerformed
        // TODO add your handling code here:
        
        AddFamilyJPanel addFamilyJPanel  = new AddFamilyJPanel(userProcessContainer,dependents,userAccount);
        userProcessContainer.add("AddFamily",addFamilyJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_addYourFamilyjButtonActionPerformed

    private void giveYourHealthRecordjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveYourHealthRecordjButtonActionPerformed
        // TODO add your handling code here:
        AddHealthRecordJPanel addHealthRecordJPanel  = new AddHealthRecordJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("AddHealthRecord",addHealthRecordJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_giveYourHealthRecordjButtonActionPerformed

    private void viewTransactionsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionsjButtonActionPerformed
        // TODO add your handling code here:
         ViewTransactionsJPanel viewTransactionsJPanel  = new ViewTransactionsJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("viewTransactions",viewTransactionsJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer); 
    }//GEN-LAST:event_viewTransactionsjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        UpdateMaritalStatusAndEmploymentStatusJPanel updateMaritalStatusAndEmploymentStatusJPanel  = new UpdateMaritalStatusAndEmploymentStatusJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("Update Marital Status", updateMaritalStatusAndEmploymentStatusJPanel);

        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AlertsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlertsjButtonActionPerformed
        // TODO add your handling code here:
        AutoDebitJPanel autoDebitJPanel  = new AutoDebitJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("autoDebit",autoDebitJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_AlertsjButtonActionPerformed

    private void alertsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertsjButtonActionPerformed
        // TODO add your handling code here:\
        AlertsJPanel alertsJPanel  = new AlertsJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("autoDebit",alertsJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_alertsjButtonActionPerformed

    private void viewPaymentPlansjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentPlansjButtonActionPerformed
        // TODO add your handling code here:
        PaymentHistoryJPanel paymentHistoryJPanel  = new PaymentHistoryJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("paymentHistory",paymentHistoryJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewPaymentPlansjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlertsjButton;
    private javax.swing.JButton addYourFamilyjButton;
    private javax.swing.JButton alertsjButton;
    private javax.swing.JButton giveYourHealthRecordjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JButton payYourPremiumjButton;
    private javax.swing.JButton viewPaymentPlansjButton;
    private javax.swing.JButton viewTransactionsjButton;
    private javax.swing.JButton viewYourFinancialAccountjButton;
    private javax.swing.JButton viewYourOffersjButton;
    // End of variables declaration//GEN-END:variables
}
