/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Invoice.Invoice;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class ViewInvoicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInvoicesJPanel
     */
    JPanel UserProcessContainer;
    Invoice invoice;
    UserAccount userAccount;
    public ViewInvoicesJPanel(JPanel UserProcessContainer,Invoice invoice,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.invoice = invoice;
        this.userAccount = userAccount;
        invoiceIDjTextField.setText(String.valueOf(1));
        offerNamejTextField.setText(invoice.getOrder().getOffer().getOfferName()) ;
        amountBeforejTextField.setText(String.valueOf(invoice.getOrder().getOffer().getPremium()));
        amountAfterjTextField.setText(String.valueOf(invoice.getOtherAmount()));
        subjTextField.setText(String.valueOf(invoice.getSubsidy()));
        fpjTextField.setText(String.valueOf(invoice.getPrice()));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        invoiceIDjTextField = new javax.swing.JTextField();
        offerNamejTextField = new javax.swing.JTextField();
        amountBeforejTextField = new javax.swing.JTextField();
        amountAfterjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        subjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fpjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View Your Invoice");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 42, -1, -1));

        jLabel2.setText("Invoice Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 88, -1, -1));

        jLabel3.setText("Offer Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 143, -1, -1));

        jLabel5.setText("Base Premium");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 201, -1, -1));

        jLabel6.setText("Other Amounts");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 254, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 347, -1, -1));

        invoiceIDjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceIDjTextFieldActionPerformed(evt);
            }
        });
        add(invoiceIDjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 85, 91, -1));
        add(offerNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 140, 91, -1));
        add(amountBeforejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 198, 91, -1));
        add(amountAfterjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 251, 91, -1));

        jLabel7.setText("Subsidy");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 308, -1, -1));
        add(subjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 305, 91, -1));

        jLabel4.setText("Final Price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 353, -1, -1));
        add(fpjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 350, 91, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceIDjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceIDjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceIDjTextFieldActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountAfterjTextField;
    private javax.swing.JTextField amountBeforejTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField fpjTextField;
    private javax.swing.JTextField invoiceIDjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField offerNamejTextField;
    private javax.swing.JTextField subjTextField;
    // End of variables declaration//GEN-END:variables
}
