/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AccountsEmployee;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AccountsAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountsAdminWorkAreaJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    Business business;
    public AccountsAdminWorkAreaJPanel(JPanel UserProcessContainer,UserAccount userAccount,Enterprise enterprise,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewInvoicesjButton = new javax.swing.JButton();
        viewOrdersjButton = new javax.swing.JButton();
        viewPaymentsjButton = new javax.swing.JButton();
        viewPaymentPlansjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setText("Accounts Work Area");

        viewInvoicesjButton.setText("View Invoices");
        viewInvoicesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInvoicesjButtonActionPerformed(evt);
            }
        });

        viewOrdersjButton.setText("View Orders");
        viewOrdersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersjButtonActionPerformed(evt);
            }
        });

        viewPaymentsjButton.setText("View Payments");
        viewPaymentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentsjButtonActionPerformed(evt);
            }
        });

        viewPaymentPlansjButton.setText("View Payment Plans");
        viewPaymentPlansjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentPlansjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Staff");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Manage UserAccount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewInvoicesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(viewOrdersjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPaymentsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPaymentPlansjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewInvoicesjButton)
                    .addComponent(viewPaymentsjButton))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewOrdersjButton)
                    .addComponent(viewPaymentPlansjButton))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewInvoicesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInvoicesjButtonActionPerformed
        // TODO add your handling code here:
        ViewAllCustomerInvoicesJPanel viewAllCustomerInvoicesJPanel  = new ViewAllCustomerInvoicesJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("viewCustomerInvoices",viewAllCustomerInvoicesJPanel );
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer); 
        
    }//GEN-LAST:event_viewInvoicesjButtonActionPerformed

    private void viewOrdersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersjButtonActionPerformed
        // TODO add your handling code here:
         ViewOrdersJPanel viewOrdersJPanel  = new ViewOrdersJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("viewOrders",viewOrdersJPanel );
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer); 
        
    }//GEN-LAST:event_viewOrdersjButtonActionPerformed

    private void viewPaymentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentsjButtonActionPerformed
        // TODO add your handling code here:
        
       
        ViewCustomerPaymentsJPanel viewCustomerPaymentsJPanel  = new ViewCustomerPaymentsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("viewCustomerPayments",viewCustomerPaymentsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);        
                
    }//GEN-LAST:event_viewPaymentsjButtonActionPerformed

    private void viewPaymentPlansjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentPlansjButtonActionPerformed
        // TODO add your handling code here:
        
        ViewAllCustomerPaymentPlansJPanel viewAllCustomerPaymentPlansJPanel  = new ViewAllCustomerPaymentPlansJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("viewPaymentPlans",viewAllCustomerPaymentPlansJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_viewPaymentPlansjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageAccountsEmployeeJPanel manageAccountsEmployeeJPanel  = new ManageAccountsEmployeeJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("ManageAccountsEmployee",manageAccountsEmployeeJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ManageAccountsUserAccountsJPanel manageAccountsUserAccountsJPanel  = new ManageAccountsUserAccountsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("ManagementUserA/c",manageAccountsUserAccountsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewInvoicesjButton;
    private javax.swing.JButton viewOrdersjButton;
    private javax.swing.JButton viewPaymentPlansjButton;
    private javax.swing.JButton viewPaymentsjButton;
    // End of variables declaration//GEN-END:variables
}
