/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AccountsEmployee;

import Business.AccountsEmployeeRole;
import Business.Employee.Employee;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddAccountsEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddAccountsEmployeeJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    public AddAccountsEmployeeJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNamejTextField1 = new javax.swing.JTextField();
        statejTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lastNamejTextField1 = new javax.swing.JTextField();
        agejTextField1 = new javax.swing.JTextField();
        backjButton1 = new javax.swing.JButton();
        userNamejTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ad1jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ad2jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        ssnjTextField = new javax.swing.JTextField();
        cityjTextField1 = new javax.swing.JTextField();
        addjButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        departmentjTextField1 = new javax.swing.JTextField();
        zipjTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(firstNamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 55, 95, -1));
        add(statejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 371, 95, -1));

        jLabel16.setText("Address Line1");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 236, -1, -1));
        add(lastNamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 100, 95, -1));
        add(agejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 143, 95, -1));

        backjButton1.setText("Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 471, -1, -1));

        userNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNamejTextFieldActionPerformed(evt);
            }
        });
        add(userNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 55, 83, -1));

        jLabel19.setText("UserAccount");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 58, -1, -1));

        jLabel18.setText("First Name");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 58, -1, -1));
        add(ad1jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 236, 95, -1));

        jLabel17.setText("State");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 374, -1, -1));

        jLabel11.setText("City");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 329, -1, -1));

        jLabel20.setText("Password");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 103, -1, -1));

        jLabel12.setText("Zip");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 418, -1, -1));

        ad2jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad2jTextField1ActionPerformed(evt);
            }
        });
        add(ad2jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 280, 95, -1));

        jLabel21.setText("SSN");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 146, -1, -1));

        jLabel5.setText("Age");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 146, -1, -1));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 100, 83, -1));

        jLabel13.setText("Address Line2");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 283, -1, -1));
        add(ssnjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 143, 83, -1));
        add(cityjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 326, 95, -1));

        addjButton1.setText("Add");
        addjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton1ActionPerformed(evt);
            }
        });
        add(addjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 471, -1, -1));

        jLabel14.setText("Last Name");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 103, -1, -1));

        departmentjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentjTextField1ActionPerformed(evt);
            }
        });
        add(departmentjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 187, 95, -1));
        add(zipjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 415, 95, -1));

        jLabel15.setText("Department");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void userNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNamejTextFieldActionPerformed

    private void ad2jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad2jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad2jTextField1ActionPerformed

    private void addjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton1ActionPerformed
        // TODO add your handling code here:
        if(firstNamejTextField1.getText().length() == 0 ||
            lastNamejTextField1.getText().length() == 0 ||
            agejTextField1.getText().length() == 0 ||
            departmentjTextField1.getText().length() == 0  ||
            ad1jTextField1.getText().length() == 0 ||
            cityjTextField1.getText().length() == 0 ||
            statejTextField1.getText().length() == 0||
            zipjTextField1 .getText().length() == 0   ||
            userNamejTextField.getText().length() == 0 ||
            jPasswordField1.getText().length() == 0
            || ssnjTextField.getText().length() == 0)

        {
            JOptionPane.showMessageDialog(null, "Please enter text");

        }
        else
        {
            try {
                Integer.parseInt(zipjTextField1.getText());
                Integer.parseInt(ssnjTextField.getText());

            } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(null, "Zip Must be a number");
                return;
            }
            Employee employee = userAccount.getExchangeEnterprise().getAccountsOrganization().getEmployeeDirectory().newEmployee();
            UserAccount userAccount1 = userAccount.getExchangeEnterprise().getTreasuryOrganization().getUserAccountDirectory().newUserAccount();
            employee.setFirstName(firstNamejTextField1.getText());
            employee.setLastName(lastNamejTextField1.getText());
            employee.setAge(Integer.parseInt(agejTextField1.getText()));
            employee.setDepartment("Accounts");

            employee.getAddress().setAddressLine1(ad1jTextField1.getText());
            employee.getAddress().setAddressLine2(ad2jTextField1.getText());
            employee.getAddress().setCity(cityjTextField1.getText());
            employee.getAddress().setState(statejTextField1.getText());
            employee.getAddress().setZip(Integer.parseInt(zipjTextField1.getText()));
            employee.setSSN(Integer.parseInt(ssnjTextField.getText()));
            AccountsEmployeeRole insuranceTreasuryRole= new  AccountsEmployeeRole();
            userAccount1.setUserName(userNamejTextField.getText());
            userAccount1.setPassword(jPasswordField1.getText());
            userAccount1.setInsuranceEnterprise(userAccount.getInsuranceEnterprise());
            userAccount1.setRole(insuranceTreasuryRole);
            userAccount1.setEnterprise(userAccount.getInsuranceEnterprise());
            userAccount1.setPerson(employee);
            userAccount1.setStatus(true);
            JOptionPane.showMessageDialog(null, "Employee Created");
        }
    }//GEN-LAST:event_addjButton1ActionPerformed

    private void departmentjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentjTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad1jTextField1;
    private javax.swing.JTextField ad2jTextField1;
    private javax.swing.JButton addjButton1;
    private javax.swing.JTextField agejTextField1;
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField cityjTextField1;
    private javax.swing.JTextField departmentjTextField1;
    private javax.swing.JTextField firstNamejTextField1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField lastNamejTextField1;
    private javax.swing.JTextField ssnjTextField;
    private javax.swing.JTextField statejTextField1;
    private javax.swing.JTextField userNamejTextField;
    private javax.swing.JTextField zipjTextField1;
    // End of variables declaration//GEN-END:variables
}
