/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AccountsEmployee;

import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.UserAccount;
import UserInterface.Treasurary.ManageTreasuryUserAccountsJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ManageAccountsEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountsEmployeeJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    EmployeeDirectory employeeDirectory;
    public ManageAccountsEmployeeJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        employeeDirectory = userAccount.getExchangeEnterprise().getAccountsOrganization().getEmployeeDirectory();
        Refresh();
    }
    
    public void Refresh()
    {
          int rowCount = employeejTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)employeejTable.getModel()).removeRow(i);
       }
        
        ArrayList<Employee> eList = employeeDirectory.getEmployeeDirectory();
        
        for(Employee e : eList)
        {
                       
          
            Object row[] = new Object[3];
            
            row[0] = e.getFirstName();
            row[1] = e.getLastName();
            
            row[2] = "Accounts";
            
            
            
            DefaultTableModel defTableModel = (DefaultTableModel)employeejTable.getModel();
                    defTableModel.addRow(row);
           
            
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeejTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addjButton.setText("Add");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        add(addjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 310, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 371, -1, -1));

        employeejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Department"
            }
        ));
        jScrollPane1.setViewportView(employeejTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 138, -1, 99));

        jLabel1.setText("Manage Employees");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 42, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        AddAccountsEmployeeJPanel addAccountsEmployeeJPanel  = new AddAccountsEmployeeJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("addAccountsEmployee",addAccountsEmployeeJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_addjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTable employeejTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
