/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AccountsEmployee;

import Business.Customer;
import Business.CustomerDirectory;
import Business.PaymentPlan.PaymentPlan;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ViewAllCustomerPaymentPlansJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllCustomerPaymentPlansJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    CustomerDirectory customerDirectory;
    public ViewAllCustomerPaymentPlansJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
       customerDirectory = userAccount.getExchangeEnterprise().getCustomerDirectory();
       customerjComboBox.removeAllItems();
        for(Customer c : customerDirectory.getCustomerDirectory())
        {
            customerjComboBox.addItem(c);
        }
        
    }

    public void Refresh()
    {
        Customer selectedCustomer = (Customer)customerjComboBox.getSelectedItem();
        ArrayList<PaymentPlan> ppList = selectedCustomer.getPaymentSchedule().getPaymentSchedule();
         int rowCount = paymentPlanjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)paymentPlanjTable.getModel()).removeRow(i);
       }
       for(PaymentPlan  p: ppList)
        {
                       
           
            Object row[] = new Object[5];
            
            row[0] = p.getPaymentId();
            row[1] = p.getDate();
            row[2] = p.getType();
            row[3] = p.getStatus();
//            DecimalFormat df = new DecimalFormat("#.##");
//            row[4] = df.format(p.getInstallment());
            
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)paymentPlanjTable.getModel();
                    defTableModel.addRow(row);
           
            
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        customerjComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        displayResultsjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentPlanjTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 255, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View Payment Plans");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 23, -1, -1));

        add(customerjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 67, 121, -1));

        jLabel2.setText("Customer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 70, -1, -1));

        displayResultsjButton.setText("Display Results");
        displayResultsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayResultsjButtonActionPerformed(evt);
            }
        });
        add(displayResultsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 66, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 391, -1, -1));

        paymentPlanjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payment ID", "Payment Due Date", "Payment Type", "Payment Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(paymentPlanjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 132, -1, 89));
    }// </editor-fold>//GEN-END:initComponents

    private void displayResultsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayResultsjButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_displayResultsjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox customerjComboBox;
    private javax.swing.JButton displayResultsjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paymentPlanjTable;
    // End of variables declaration//GEN-END:variables
}
