/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AccountsEmployee;

import Business.Invoice.Invoice;
import Business.Invoice.InvoiceCatalog;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ViewAllCustomerInvoicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllCustomerInvoicesJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    InvoiceCatalog invoiceCatalogue;
    public ViewAllCustomerInvoicesJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer =UserProcessContainer;
        this.userAccount = userAccount;
        invoiceCatalogue = userAccount.getExchangeEnterprise().getInvoiceCatalog();
        Refresh();
    }

    public void Refresh()
    {
        int rowCount = invoicesjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)invoicesjTable.getModel()).removeRow(i);
       }
                        
        for(Invoice i : invoiceCatalogue.getInvoiceCatalog())
        {
         
            Object row[] = new Object[5];
            
            row[0] = i.getOrder().getCustomer();
            row[1] = i.getOrder().getOffer();
            row[2] = i.getPrice();
            row[3] = i.getSubsidy();
            row[4] = i.getOtherAmount();
            
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)invoicesjTable.getModel();
                    defTableModel.addRow(row);
           }     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View Invoices");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 22, -1, -1));

        invoicesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer", "Offer", "Final Amount", "Subsidy", "OtherAdded Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(invoicesjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 54, -1, 90));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 333, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTable invoicesjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
