/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AccountsEmployee;

import Business.Customer;
import Business.CustomerDirectory;
import Business.PaymentPlan.PaymentPlan;
import Business.Transaction.Transaction;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ViewCustomerPaymentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerPaymentsJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    CustomerDirectory customerDirectory;
    ArrayList<Transaction> tList;
    public ViewCustomerPaymentsJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        customerDirectory = userAccount.getExchangeEnterprise().getCustomerDirectory();
        tList = new ArrayList<Transaction> ();
        customerjComboBox.removeAllItems();
        for(Customer c : customerDirectory.getCustomerDirectory())
        {
            customerjComboBox.addItem(c);
        }
    }
    private void Refresh()
    {
        Customer selectedCustomer = (Customer)customerjComboBox.getSelectedItem();
        ArrayList<PaymentPlan> ppList = selectedCustomer.getPaymentSchedule().getPaymentSchedule();
       for(PaymentPlan pp : ppList )
       {
           for(Transaction t : pp.getTransactionHistory().getTransactionHistory())
           {
               tList.add(t);
           }
       }
       int rowCount = transactionjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)transactionjTable.getModel()).removeRow(i);
       }
                        
        for(Transaction t1 : tList)
        {
         
            Object row[] = new Object[5];
            
            row[0] = t1.getTransactionId();
            row[1] = t1.getAmount();
            row[2] = t1;
            row[3] = t1.getCustomer();
            row[4] = t1.getPaymentPlan().getInvoice().getOrder().getOffer().getInsuranceEnterprise();
            
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)transactionjTable.getModel();
                    defTableModel.addRow(row);
           }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerjComboBox = new javax.swing.JComboBox();
        backjButton = new javax.swing.JButton();
        displayResultsjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionjTable = new javax.swing.JTable();

        jLabel3.setText("Send Payments To Concerned Parties");

        setBackground(new java.awt.Color(0, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View Payments ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 23, -1, -1));

        jLabel2.setText("Customer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 66, -1, -1));

        add(customerjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 63, 121, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 278, -1, -1));

        displayResultsjButton.setText("Display Results");
        displayResultsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayResultsjButtonActionPerformed(evt);
            }
        });
        add(displayResultsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 62, -1, -1));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 314, -1, -1));

        transactionjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Amount", "Transaction Date", "Customer", "Insurance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 138, -1, 87));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void displayResultsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayResultsjButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_displayResultsjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox customerjComboBox;
    private javax.swing.JButton displayResultsjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable transactionjTable;
    // End of variables declaration//GEN-END:variables
}
