/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AccountsEmployee;

import Business.Order.MasterOrderCatalog;
import Business.Order.Order;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ViewOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrdersJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    MasterOrderCatalog masterOrderCatalog;
    public ViewOrdersJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        masterOrderCatalog = userAccount.getExchangeEnterprise().getMasterOrderCatalog();
        Refresh();
    }
  
    public void Refresh()
    {
        int rowCount = ordersjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)ordersjTable.getModel()).removeRow(i);
       }
                        
        for(Order o : masterOrderCatalog.getMasterOrderCatalog())
        {
         
            Object row[] = new Object[3];
            
            row[0] = o.getCustomer();
            row[1] = o.getOffer();
            row[2] = o.getOffer().getInsuranceEnterprise();
            
            
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)ordersjTable.getModel();
                    defTableModel.addRow(row);
           }     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backjButton.setText("Back >");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 322, -1, -1));

        ordersjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer", "Offer Name", "Insurance Issuer"
            }
        ));
        jScrollPane1.setViewportView(ordersjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 62, -1, 91));

        jLabel1.setText("View Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordersjTable;
    // End of variables declaration//GEN-END:variables
}
