/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.InsuranceEcoSystem.Organization;
import Business.UserAccount;
import Db4o.Db40Util;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    Business business;
    
    public MainJFrame() {
        initComponents();
        business = Db40Util.getBusiness();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainjSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginjButton = new javax.swing.JButton();
        registerjButton = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        logoffjButton = new javax.swing.JButton();
        UserProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainjSplitPane.setDividerLocation(230);

        jLabel2.setText("UserName");

        jLabel3.setText("Password");

        loginjButton.setText("Login");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });

        registerjButton.setText("Sign Up");
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });

        logoffjButton.setText("Log Off");
        logoffjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoffjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(loginjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(userNamejTextField))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(loginjButton)
                .addGap(18, 18, 18)
                .addComponent(registerjButton)
                .addGap(18, 18, 18)
                .addComponent(logoffjButton)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        mainjSplitPane.setLeftComponent(jPanel1);

        UserProcessContainer.setLayout(new java.awt.CardLayout());
        mainjSplitPane.setRightComponent(UserProcessContainer);

        getContentPane().add(mainjSplitPane, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        // TODO add your handling code here:
        CustomerTypeJPanel customerTypeJPanel  = new CustomerTypeJPanel(UserProcessContainer,business);
        UserProcessContainer.add("CustomerType",customerTypeJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_registerjButtonActionPerformed

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
        // TODO add your handling code here:
        String userName = userNamejTextField.getText();
        String password = jPasswordField.getText();
       //UserAccount userAccount= business.getExchangeEnterprise().getUserAccountDirectory().authenticate(userName, password);
        Enterprise enterprise=null;
        UserAccount userAccount= business.getUserAccountDirectory().authenticate(userName, password);
        if(userAccount==null){
            for(Enterprise e:business.getEnterpriseDirectory().getEnterpriseDirectory()){
                userAccount=e.getUserAccountDirectory().authenticate(userName, password);
            
            if(userAccount==null){
                for(Organization o:e.getOrganizationDirectory().getOrganizationDirectory()){
                    userAccount=o.getUserAccountDirectory().authenticate(userName, password);
                    
                    if(userAccount!=null){
                        System.out.println("username is "+userAccount.getUserName());
              enterprise=e; 
              
              break;
            }
                    
                }
            }
            if(userAccount !=null)
            {
                break;
            }
//            if(userAccount!=null){
//              enterprise=e; 
//              
//              break;
//            }
            }
        }
        else{
            enterprise=business;
        }
        
        if(userAccount == null)
        {
            
            
            JOptionPane.showMessageDialog(null, "Invalid Login");
            return;
        }
        UserProcessContainer.removeAll();
        JPanel jPanel= userAccount.getRole().getWorkArea().createView(UserProcessContainer,userAccount,enterprise,business);
        UserProcessContainer.add("AdminWA",jPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_loginjButtonActionPerformed

    private void logoffjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffjButtonActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.removeAll();
         UserProcessContainer.updateUI();
         Db40Util.storeObject(business);
//         CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
//        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_logoffjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserProcessContainer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton loginjButton;
    private javax.swing.JButton logoffjButton;
    private javax.swing.JSplitPane mainjSplitPane;
    private javax.swing.JButton registerjButton;
    private javax.swing.JTextField userNamejTextField;
    // End of variables declaration//GEN-END:variables
}
