/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExchangeAdmin;

import Business.Business;
import Business.Customer;
import Business.CustomerRole;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.EnterpriseDirectory;
import Business.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddInsuranceIssuerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddInsuranceIssuerJPanel
     */
    JPanel UserProcessContainer;
    Business business;
    EnterpriseDirectory enterpriseDirectory;
    public AddInsuranceIssuerJPanel(JPanel UserProcessContainer,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        enterpriseDirectory = business.getEnterpriseDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        insuranceNamejTextField = new javax.swing.JTextField();
        registerjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        jLabel1.setText("Add Insurance Issuer");

        jLabel2.setText("Insurance Issuer Name");

        insuranceNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceNamejTextFieldActionPerformed(evt);
            }
        });

        registerjButton.setText("Register");
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(insuranceNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addGap(49, 49, 49)
                .addComponent(registerjButton)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(insuranceNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerjButton)
                    .addComponent(backjButton))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insuranceNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceNamejTextFieldActionPerformed

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        // TODO add your handling code here:
        InsuranceEnterprise insuranceEnterprise =(InsuranceEnterprise) enterpriseDirectory.newEnterprise(Enterprise.Type.Insurance.toString());
        if(insuranceNamejTextField.getText().length() == 0)
        {
                
//                adrLine1jTextField.getText().length() == 0 ||
//                statejTextField.getText().length() == 0||
//                zipjTextField .getText().length() == 0 ||
//                 userNamejTextField.getText().length() == 0 ||
//                 jPasswordField.getText().length()== 0)
         
             JOptionPane.showMessageDialog(null, "Some of the feilds are null");
         }
         else
         {
        
        insuranceEnterprise.setInsuranceName(insuranceNamejTextField.getText());
        insuranceEnterprise.setStatus("Yet To Register With Exchange");
        JOptionPane.showMessageDialog(null, "Insurance Issuer Added");
        
    }//GEN-LAST:event_registerjButtonActionPerformed
    }
    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField insuranceNamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registerjButton;
    // End of variables declaration//GEN-END:variables
}
