/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExchangeAdmin;

import Business.Business;
import Business.Customer;
import Business.CustomerDirectory;
import Business.Enterprise.Enterprise;
import Business.PaymentPlan.PaymentPlan;
import Business.Transaction.Transaction;
import Business.UserAccount;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AdminExchangeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminExchangeWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Business business;
    Enterprise enterprise;
    CustomerDirectory customerDirectory;
    Date date;
     Date date1;
     Date date2;
    public AdminExchangeWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        customerDirectory = userAccount.getExchangeEnterprise().getCustomerDirectory();
        this.business = business;
        Calendar cal = Calendar.getInstance();
     date = cal.getTime();
     SimpleDateFormat formatter= new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(cal.getTime());
     try {
                        date2 = new SimpleDateFormat("MMM/dd/yyyy", Locale.ENGLISH).parse(dateNow);
                    } catch (ParseException ex) {
                        System.out.println("in catch");
                        Logger.getLogger(AdminExchangeWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addMarketjButton = new javax.swing.JButton();
        addAdminForInsuranceIssuersjButton = new javax.swing.JButton();
        approveInsurancePlansjButton = new javax.swing.JButton();
        viewWorkRequestsjButton = new javax.swing.JButton();
        manageUserAccountsjButton = new javax.swing.JButton();
        approveSmallBusinessjButton = new javax.swing.JButton();
        TimerjButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Exchange Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 51, -1, -1));

        addMarketjButton.setText("Add Market for Exchange");
        addMarketjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarketjButtonActionPerformed(evt);
            }
        });
        add(addMarketjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 101, 200, 20));

        addAdminForInsuranceIssuersjButton.setText("Approve Insurance Issuers");
        addAdminForInsuranceIssuersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminForInsuranceIssuersjButtonActionPerformed(evt);
            }
        });
        add(addAdminForInsuranceIssuersjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 101, 200, 20));

        approveInsurancePlansjButton.setText("Approve Insurance Plans");
        approveInsurancePlansjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveInsurancePlansjButtonActionPerformed(evt);
            }
        });
        add(approveInsurancePlansjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 168, 200, 20));

        viewWorkRequestsjButton.setText("View BI Reports");
        viewWorkRequestsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWorkRequestsjButtonActionPerformed(evt);
            }
        });
        add(viewWorkRequestsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 168, 200, 20));

        manageUserAccountsjButton.setText("Manage UserAccounts");
        manageUserAccountsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountsjButtonActionPerformed(evt);
            }
        });
        add(manageUserAccountsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 238, 200, 20));

        approveSmallBusinessjButton.setText("Approve Small Business Plans");
        approveSmallBusinessjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveSmallBusinessjButtonActionPerformed(evt);
            }
        });
        add(approveSmallBusinessjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 238, 200, 20));

        TimerjButton.setText("Run Schedules Receivables");
        TimerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimerjButtonActionPerformed(evt);
            }
        });
        add(TimerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 307, 200, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void addMarketjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarketjButtonActionPerformed
        // TODO add your handling code here:
        AddMarketJPanel addMarketJPanel  = new AddMarketJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("addMarket",addMarketJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_addMarketjButtonActionPerformed

    private void approveInsurancePlansjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveInsurancePlansjButtonActionPerformed
        // TODO add your handling code here:
        ApproveInsurancePlansJPanel approveInsurancePlansJPanel  = new ApproveInsurancePlansJPanel(userProcessContainer,userAccount,business);
        userProcessContainer.add("approveInsurancePlans",approveInsurancePlansJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_approveInsurancePlansjButtonActionPerformed

    private void addAdminForInsuranceIssuersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminForInsuranceIssuersjButtonActionPerformed
        // TODO add your handling code here:
        ApproveInsuranceIssuerJPanel approveInsuranceIssuerJPanel  = new ApproveInsuranceIssuerJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("Approve Issuer",approveInsuranceIssuerJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

    }//GEN-LAST:event_addAdminForInsuranceIssuersjButtonActionPerformed

    private void manageUserAccountsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountsjButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountsJPanel manageUserAccountsJPanel  = new ManageUserAccountsJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("manageUserAccounts",manageUserAccountsJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountsjButtonActionPerformed

    private void approveSmallBusinessjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveSmallBusinessjButtonActionPerformed
        // TODO add your handling code here:
        ApproveSmallBusinessPlansJPanel approveSmallBusinessPlansJPanel = new ApproveSmallBusinessPlansJPanel(userProcessContainer,userAccount,business);
        userProcessContainer.add("approveSmallBusiness",approveSmallBusinessPlansJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_approveSmallBusinessjButtonActionPerformed

    private void viewWorkRequestsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWorkRequestsjButtonActionPerformed
        // TODO add your handling code here:
        BusinessReportsJPanel businessReportsJPanel = new BusinessReportsJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("BI Reports",businessReportsJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewWorkRequestsjButtonActionPerformed

    private void TimerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimerjButtonActionPerformed
        // TODO add your handling code here:
       getScheduledPayments();
       JOptionPane.showMessageDialog(null, "Schedule Completed");
    }//GEN-LAST:event_TimerjButtonActionPerformed

    public void getScheduledPayments()
    {
        for(Customer c : customerDirectory.getCustomerDirectory())
        {
            if(c.getPaymentSchedule().getPaymentSchedule().size()> 0)
            {
                System.out.println("in if1");
        if(c.getAutoDebit().isAutoDebitStatus())
            {
                System.out.println("in if2");
                for(PaymentPlan pp : c.getPaymentSchedule().getPaymentSchedule())
                {
                     
            //MM/dd/yyyy HH:mm:ss
           
                    try {
                        date1 = new SimpleDateFormat("MMM/dd/yyyy", Locale.ENGLISH).parse(pp.getDate());
                    } catch (ParseException ex) {
                        System.out.println("in catch");
                        Logger.getLogger(AdminExchangeWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   
                       if(date2.equals(date1))
                       {
                           
                           SimpleDateFormat formatter= new SimpleDateFormat("yyyy/MMM/dd HH:mm:ss");
                           String dateNow = formatter.format(date);
                           Transaction t = pp.getTransactionHistory().newTransaction();
                           t.setPaymentPlan(pp);
                           t.setTransactionId(1);
                           t.setPaidDate(dateNow);
                           t.setAmount(pp.getInstallment());
                           t.setCustomer(c);
                           pp.setStatus("Paid");
                           pp.setInstallment(0.0);
                       }
                       
        
                
            }
        }
        }
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TimerjButton;
    private javax.swing.JButton addAdminForInsuranceIssuersjButton;
    private javax.swing.JButton addMarketjButton;
    private javax.swing.JButton approveInsurancePlansjButton;
    private javax.swing.JButton approveSmallBusinessjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageUserAccountsjButton;
    private javax.swing.JButton viewWorkRequestsjButton;
    // End of variables declaration//GEN-END:variables
}
