/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExchangeAdmin;

import Business.Business;
import Business.UserAccount;
import Business.WorkQueue;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ApproveInsurancePlansJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveInsurancePlansJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Business business;
    public ApproveInsurancePlansJPanel(JPanel UserProcessContainer,UserAccount userAccount,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        Refresh();
    }
    
    public void Refresh()
    {
       // WorkQueue workQueue = userAccount.getRole().getWorkArea().getWorkQueue();
        WorkQueue workQueue = userAccount.getExchangeEnterprise().getReceivingQueue();
        ArrayList<WorkRequest> workQueueList = workQueue.getWorkQueue();
        int rowCount = exchangeAdminjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)exchangeAdminjTable.getModel()).removeRow(i);
       }
                        
        for(WorkRequest wR : workQueueList)
        {
                       
          if(wR.getType().equals("Offer"))
           { 
            Object row[] = new Object[4];
            
            row[0] = wR.getOffer();
            row[1] = wR.getInsuranceEnterprise();
            row[2] = wR.getOffer().getMarket();
            row[3] = wR;
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)exchangeAdminjTable.getModel();
                    defTableModel.addRow(row);
           }     
            
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        exchangeAdminjTable = new javax.swing.JTable();
        approvejButton = new javax.swing.JButton();
        rejectjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        exchangeAdminjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OfferName", "Insurance Issuer", "Market", "Status"
            }
        ));
        jScrollPane1.setViewportView(exchangeAdminjTable);

        approvejButton.setText("Approve");
        approvejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvejButtonActionPerformed(evt);
            }
        });

        rejectjButton.setText("Reject");
        rejectjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectjButtonActionPerformed(evt);
            }
        });

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Approve Insurance Plans");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(rejectjButton)
                .addGap(65, 65, 65)
                .addComponent(approvejButton)
                .addGap(48, 48, 48)
                .addComponent(backjButton)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approvejButton)
                    .addComponent(rejectjButton)
                    .addComponent(backjButton))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rejectjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowCount = exchangeAdminjTable.getSelectedRowCount(); 
                  if(selectedRowCount == 0)
       {
        JOptionPane.showMessageDialog(null,"Please select row");
        return;
       }
       
       if(selectedRowCount <= 0 || selectedRowCount> exchangeAdminjTable.getRowCount())
       {
           return;
       }
       
       int selectedRow =  exchangeAdminjTable.getSelectedRow();
       WorkRequest selectedWR = (WorkRequest)exchangeAdminjTable.getValueAt(selectedRow, 3);
       selectedWR.setStatus("Rejected");
       selectedWR.getOffer().setStatus("Rejected");
       Refresh();
       JOptionPane.showMessageDialog(null, "Work Request Rejected");
    }//GEN-LAST:event_rejectjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void approvejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowCount = exchangeAdminjTable.getSelectedRowCount(); 
                  if(selectedRowCount == 0)
       {
        JOptionPane.showMessageDialog(null,"Please select row");
        return;
       }
       
       if(selectedRowCount <= 0 || selectedRowCount> exchangeAdminjTable.getRowCount())
       {
           return;
       }
       
       int selectedRow =  exchangeAdminjTable.getSelectedRow();
       WorkRequest selectedWR = (WorkRequest)exchangeAdminjTable.getValueAt(selectedRow, 3);
       selectedWR.setStatus("Approved");
       selectedWR.getOffer().setStatus("Approved");
       userAccount.getExchangeEnterprise().getOffers().add(selectedWR.getOffer());
       Refresh();
       JOptionPane.showMessageDialog(null, "Work Request Approved");
    }//GEN-LAST:event_approvejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvejButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTable exchangeAdminjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejectjButton;
    // End of variables declaration//GEN-END:variables
}
