/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExchangeAdmin;

import Business.Enterprise.InsuranceEnterprise;
import Business.Offer;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class BusinessReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BusinessReportsJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    public BusinessReportsJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        Refresh();
        Refresh2();
    }
    
    public void Refresh()
    {
        int rowCount = insurancejTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)insurancejTable.getModel()).removeRow(i);
       }
                        
        for(InsuranceEnterprise i: userAccount.getExchangeEnterprise().getInsuranceIssuers())
        {
         for(Offer o : i.getOffers().getOffers())
         {
            Object row[] = new Object[4];
            
            row[0] = i;
            row[1] = o.getOfferName();
            row[2] = o.getSalesByPlans();
            row[3] = o.getCustomerList().size();
            
            
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)insurancejTable.getModel();
                    defTableModel.addRow(row);
           }     
    }
    }
    
     public void Refresh2()
    {
        int rowCount = offerjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)offerjTable.getModel()).removeRow(i);
       }
                        
        for(InsuranceEnterprise i: userAccount.getExchangeEnterprise().getInsuranceIssuers())
        {
         for(Offer o : i.getOffers().getOffers())
         {
            Object row[] = new Object[3];
            
            row[0] = o.getOfferName();
            row[1] = o.getCustomerList().size();
            row[2] = o.getSalesByPlans();
           
            
            
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)offerjTable.getModel();
                    defTableModel.addRow(row);
           }     
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insurancejTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        offerjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 385, -1, -1));

        insurancejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Insurance Issuer", "Offer", "Total Sales", "No Of Customers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(insurancejTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 40, -1, 79));

        jLabel1.setText("Sales By Insurance");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, -1));

        offerjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Offer", "NoOfCustomers", "Total Sales Done"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(offerjTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 222, -1, 84));

        jLabel2.setText("Sales By Plans");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTable insurancejTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable offerjTable;
    // End of variables declaration//GEN-END:variables
}
