/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BusinessAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.EnterpriseDirectory;
import Business.Exchange.Exchange;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddExchangeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddExchangeJPanel
     */
    JPanel UserProcessContainer;
    Business business;
    EnterpriseDirectory enterpriseDirectory;
    ArrayList<String> stateList;
    ArrayList<Exchange> exchangeList;
    public AddExchangeJPanel(JPanel UserProcessContainer,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        enterpriseDirectory = business.getEnterpriseDirectory();
        stateList = new ArrayList<String>();
        exchangeList = new ArrayList<Exchange>();
        stateList.add("Alabama");
        stateList.add("Alaska");
        stateList.add("Arizona");
         stateList.add("Arkansas");
        stateList.add("California");
        stateList.add("Colorado");
        stateList.add("Connecticut");
        stateList.add("Delaware");
        stateList.add("Florida");
         stateList.add("Georgia");
        stateList.add("Hawaii");
        stateList.add("Idaho");
        stateList.add("Illinois");
        stateList.add("Minnesota");
        stateList.add("North Carolina");
         stateList.add("Texas");
        stateList.add("Indiana");
        stateList.add("Iowa");
        stateList.add("Massachusetts");
        stateList.add("Rhode Island");
        stateList.add("Newyork");
         stateList.add("Ohio");
        stateList.add("Maryland");
        stateList.add("Maine");
        for(String s : stateList)
        {
            statejComboBox.addItem(s);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exchangejTextField = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        registerjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        statejComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add Exchange");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 22, -1, -1));

        jLabel2.setText("Exchange Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 63, -1, -1));
        add(exchangejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 60, 97, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 251, -1, -1));

        registerjButton.setText("Register");
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });
        add(registerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 251, -1, -1));

        jLabel3.setText("State");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 108, -1, -1));

        add(statejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 105, 97, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        // TODO add your handling code here:
        
        String selectedState = (String)statejComboBox.getSelectedItem();
        if(exchangejTextField.getText().length() == 0)
        {

            
        JOptionPane.showMessageDialog(null, "Some of the feilds are null");
        }
        else
        {
            for(Enterprise enterprise:enterpriseDirectory.getEnterpriseDirectory())
        {
            if(enterprise.getEnterpriseName().equals("Exchange"))
            {
                if(enterprise.getState().equals(selectedState))
                {
                    JOptionPane.showMessageDialog(null, "Exchange Already Added");
                     return;
                }
            }
        }
Exchange exchange =(Exchange) enterpriseDirectory.newEnterprise(Enterprise.Type.Exchange.toString());
            exchange.setExchangeName(exchangejTextField.getText());
            exchange.setState(selectedState);
            JOptionPane.showMessageDialog(null, "Exchange Added");

    }//GEN-LAST:event_registerjButtonActionPerformed
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField exchangejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton registerjButton;
    private javax.swing.JComboBox statejComboBox;
    // End of variables declaration//GEN-END:variables
}
