/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BusinessAdmin;

import Business.AdminRole;
import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.EnterpriseDirectory;
import Business.Exchange.Exchange;
import Business.InsuranceAdminRole;
import Business.UserAccount;
import Business.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddUserAccountBusinessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddUserAccountBusinessJPanel
     */
    JPanel UserProcessContainer;
    UserAccountDirectory userAccountDirectory;
    Business business;
    BusinessAdminUserAccountsJPanel baujp;
    EnterpriseDirectory enterpriseDirectory;
    
    public AddUserAccountBusinessJPanel(JPanel UserProcessContainer,UserAccountDirectory userAccountDirectory,BusinessAdminUserAccountsJPanel baujp,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccountDirectory = userAccountDirectory;
        this.baujp = baujp;
        this.business = business;
        enterpriseDirectory = business.getEnterpriseDirectory();
        typejComboBox.removeAllItems();
        typejComboBox.addItem("Exchange Enterprise");
        typejComboBox.addItem("Insurance Enterprise");
        exchangejComboBox.removeAllItems();
        for(Enterprise enterprise:enterpriseDirectory.getEnterpriseDirectory())
        {
            if(enterprise.getEnterpriseName().equals("Exchange"))
            {
                exchangejComboBox.addItem(enterprise);
            }
        }
        
        typejComboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                try {
                    String selectedType = (String)typejComboBox.getSelectedItem();
                    if (e.getStateChange() == ItemEvent.SELECTED) {
                        if(selectedType.equals("Exchange Enterprise"))
                        {
                        insuranceEnterprisejComboBox.removeAllItems();
                        
                        
                        }
                        else if(selectedType.equals("Insurance Enterprise"))
                                {
                                    exchangejComboBox.removeAllItems();
                                    insuranceEnterprisejComboBox.removeAllItems();
                                    for(Enterprise e1:enterpriseDirectory.getEnterpriseDirectory())
                                    {
                                        if(e1.getEnterpriseName().equals("Insurance"))
                                        {
                                            insuranceEnterprisejComboBox.addItem(e1);
                                        }
                                    }
                                    
                                    
                                }
                    }
                    //throw new UnsupportedOperationException("Not supported yet.");
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        } );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exchangejComboBox = new javax.swing.JComboBox();
        typejComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        insuranceEnterprisejComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        userNamejTextField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 33, -1, -1));

        jLabel2.setText("Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 84, -1, -1));

        jLabel3.setText("Exchange");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 131, -1, -1));

        add(exchangejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 128, 100, -1));

        add(typejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 81, 100, -1));

        jLabel4.setText("Insurance Enterprise");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 177, -1, -1));

        add(insuranceEnterprisejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 174, 100, -1));

        jLabel5.setText("UserName");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 220, -1, -1));

        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 263, -1, -1));

        createjButton.setText("Create");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });
        add(createjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 289, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 289, -1, -1));
        add(userNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 217, 100, -1));
        add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 263, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        // TODO add your handling code here:
        if(userNamejTextField.getText().length() == 0 ||
                jPasswordField.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Either UserName or Password is Null");
        }
        else
        {
           
//            UserAccount userAccount = userAccountDirectory.newUserAccount();
//            String selectedType = (String)typejComboBox.getSelectedItem();
//            Exchange exchangeEnterprise = (Exchange)exchangejComboBox.getSelectedItem();
//            InsuranceEnterprise insuranceEnterprise = (InsuranceEnterprise)insuranceEnterprisejComboBox.getSelectedItem();
//            userAccount.setUserName(userNamejTextField.getText());
//            userAccount.setPassword(jPasswordField.getText());
//            userAccount.setStatus(true);
            String selectedType = (String)typejComboBox.getSelectedItem();
             UserAccount userAccount = userAccountDirectory.newUserAccount();
            if(selectedType.equals("Exchange Enterprise"))
            {
               
            
            Exchange exchangeEnterprise = (Exchange)exchangejComboBox.getSelectedItem();
            
            userAccount.setUserName(userNamejTextField.getText());
            userAccount.setPassword(jPasswordField.getText());
            userAccount.setStatus(true);
              AdminRole AdminRole = new AdminRole();
              userAccount.setRole(AdminRole); 
              userAccount.setExchangeEnterprise(exchangeEnterprise);
              userAccount.setEnterprise(exchangeEnterprise);
//              userAccount.getPerson().setFirstName("Exchange");
//              userAccount.getPerson().setLastName("Admin");
            }
            else if(selectedType.equals("Insurance Enterprise"))
            {
                 
            InsuranceEnterprise insuranceEnterprise = (InsuranceEnterprise)insuranceEnterprisejComboBox.getSelectedItem();
            userAccount.setUserName(userNamejTextField.getText());
            userAccount.setPassword(jPasswordField.getText());
            userAccount.setStatus(true);
              AdminRole AdminRole = new AdminRole();
              userAccount.setRole(AdminRole); 
              
               
               InsuranceAdminRole insuranceAdminRole = new InsuranceAdminRole();
               userAccount.setRole(insuranceAdminRole);
               userAccount.setInsuranceEnterprise(insuranceEnterprise);
               userAccount.setEnterprise(insuranceEnterprise);
//               userAccount.getPerson().setFirstName("Insurance");
//               userAccount.getPerson().setLastName("Admin");
            }
        }
    }//GEN-LAST:event_createjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
        this.baujp.Refresh();
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton createjButton;
    private javax.swing.JComboBox exchangejComboBox;
    private javax.swing.JComboBox insuranceEnterprisejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JComboBox typejComboBox;
    private javax.swing.JTextField userNamejTextField;
    // End of variables declaration//GEN-END:variables
}
