/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BusinessAdmin;

import Business.Business;
import Business.UserAccount;
import Business.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class BusinessAdminUserAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BusinessAdminUserAccountsJPanel
     */
    JPanel UserProcessContainer;
    Business business;
    UserAccountDirectory userAccountDirectory;
    public BusinessAdminUserAccountsJPanel(JPanel UserProcessContainer,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        userAccountDirectory = business.getUserAccountDirectory();
        Refresh();
    }
    
    public void Refresh()
    {
        int rowCount = businessUserAccountsjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)businessUserAccountsjTable.getModel()).removeRow(i);
       }
        
        ArrayList<UserAccount> uAList = userAccountDirectory.getUserDirectory();
        
        for(UserAccount ua : uAList)
        {
                       
          
            Object row[] = new Object[4];
            
            row[0] = ua;
            row[1] = ua.getPassword();
            
            row[2] = ua.getEnterprise(); 
            
            if(ua.isStatus())
            {
            row[3] = "Enabled";
            }
            else
            {
             row[3] = "Disabled";  
            }
            
            
            DefaultTableModel defTableModel = (DefaultTableModel)businessUserAccountsjTable.getModel();
                    defTableModel.addRow(row);
           
            
    }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        businessUserAccountsjTable = new javax.swing.JTable();
        addUserAccountjButton = new javax.swing.JButton();
        enableUserAccountjButton = new javax.swing.JButton();
        disableUserAccountjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        businessUserAccountsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UserName", "Password", "Enterprise Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(businessUserAccountsjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 14, -1, 90));

        addUserAccountjButton.setText("Add User Account");
        addUserAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserAccountjButtonActionPerformed(evt);
            }
        });
        add(addUserAccountjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 187, -1, -1));

        enableUserAccountjButton.setText("Enable User Account");
        add(enableUserAccountjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 228, -1, -1));

        disableUserAccountjButton.setText("Disable User Account");
        add(disableUserAccountjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 269, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addUserAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserAccountjButtonActionPerformed
        // TODO add your handling code here:
        AddUserAccountBusinessJPanel addUserAccountBusinessJPanel  = new AddUserAccountBusinessJPanel(UserProcessContainer,userAccountDirectory,this,business);
        UserProcessContainer.add("addUserAccount",addUserAccountBusinessJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_addUserAccountjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserAccountjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTable businessUserAccountsjTable;
    private javax.swing.JButton disableUserAccountjButton;
    private javax.swing.JButton enableUserAccountjButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
