/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceTreasury;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class InsuranceTreasuryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceTreasuryWorkAreaJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    Business business;
    public InsuranceTreasuryWorkAreaJPanel(JPanel UserProcessContainer,UserAccount userAccount,Enterprise enterprise,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPaymentsjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewPaymentsjButton.setText("View Payments By Exchange");
        viewPaymentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentsjButtonActionPerformed(evt);
            }
        });
        add(viewPaymentsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 76, 180, -1));

        jLabel1.setText("Treasury Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 20, -1, -1));

        jButton1.setText("Insurance Financial Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewPaymentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentsjButtonActionPerformed
        // TODO add your handling code here:
        ViewReceivedPaymentsJPanel viewReceivedPaymentsJPanel  = new ViewReceivedPaymentsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("ViewReceicvables",viewReceivedPaymentsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_viewPaymentsjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        InsuranceFinancialAccountJPanel insuranceFinancialAccountJPanel  = new InsuranceFinancialAccountJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("InsuranceExchangeFinancial",insuranceFinancialAccountJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewPaymentsjButton;
    // End of variables declaration//GEN-END:variables
}
