/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRegistration;

import Business.Family.Dependent;
import Business.Family.Dependents;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddFamilyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFamilyJPanel
     */
    JPanel UserProcessContainer;
    Dependents dependents;
    UserAccount  userAccount;
    public AddFamilyJPanel(JPanel UserProcessContainer, Dependents dependents,UserAccount  userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.dependents    = dependents;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNamejTextField = new javax.swing.JTextField();
        lastNamejTextField = new javax.swing.JTextField();
        agejTextField = new javax.swing.JTextField();
        SSNjTextField = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        addjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        relationjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add Family");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 26, -1, -1));

        jLabel2.setText("First Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 68, -1, -1));

        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 116, -1, -1));

        jLabel4.setText("Age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 162, -1, -1));

        jLabel5.setText("SSN");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 204, -1, -1));
        add(firstNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 65, 94, -1));

        lastNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNamejTextFieldActionPerformed(evt);
            }
        });
        add(lastNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 113, 94, -1));

        agejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextFieldActionPerformed(evt);
            }
        });
        add(agejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 162, 94, -1));
        add(SSNjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 201, 94, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 283, -1, -1));

        addjButton.setText("Add To Your Dependent List");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        add(addjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 283, -1, -1));

        jLabel6.setText("Relation");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 242, -1, -1));
        add(relationjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 239, 94, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void agejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextFieldActionPerformed

    private void lastNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNamejTextFieldActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
         if(!(userAccount.getCustomer().isMaritalStatus()))
        {
             JOptionPane.showMessageDialog(null, "Please Update Your Marital Status and then Proceed");
             return;
        }
       if(firstNamejTextField.getText().length() == 0
              || lastNamejTextField.getText().length() == 0
               || agejTextField.getText().length() == 0
               || SSNjTextField.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(null, "Some of the feilds are null");
       }
       else
    {
        try {
                   Integer.parseInt(agejTextField.getText());
                   Integer.parseInt(SSNjTextField.getText());
             
             } catch (NumberFormatException e) {
           
            JOptionPane.showMessageDialog(null, "SSN and Age Must be a Numeric");
            return;
        }
        Dependent dependent = dependents.newDependent();
        dependent.setFirstName(firstNamejTextField.getText());
        dependent.setLastName(lastNamejTextField.getText());
        dependent.setRelation(relationjTextField.getText());
        dependent.setSSN(Integer.parseInt(SSNjTextField.getText()));
        dependent.setAge(Integer.parseInt(agejTextField.getText()));
        dependent.setPerson(userAccount.getPerson());
         JOptionPane.showMessageDialog(null, "Dependent Added");
        
    }

    }//GEN-LAST:event_addjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SSNjTextField;
    private javax.swing.JButton addjButton;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastNamejTextField;
    private javax.swing.JTextField relationjTextField;
    // End of variables declaration//GEN-END:variables
}
