/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRegistration;

import Business.Person;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddHealthRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddHealthRecordJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Person person;
    public AddHealthRecordJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        person = userAccount.getPerson();
    }
    public void preExistingCheck()
    {
        if(preYesjRadioButton.isSelected())
        {
           person.setRiskFactor(person.getRiskFactor()+ 1);
        }
        else if(preNojRadioButton.isSelected())
        {
           person.setRiskFactor(person.getRiskFactor()+ 0);
        }
        
    }
    
    public void lifeTreating()
    {
        if(lifeYesjRadioButton.isSelected())
        {
            person.setRiskFactor(person.getRiskFactor()+ 1);
        }
        else if(lifeNojRadioButton.isSelected())
        {
            person.setRiskFactor(person.getRiskFactor()+ 0);
        }
    }
     public void diabetes()
    {
        if(diabYesjRadioButton.isSelected())
        {
            person.setRiskFactor(person.getRiskFactor()+ 1);
        }
        else if(diabNojRadioButton.isSelected())
        {
            person.setRiskFactor(person.getRiskFactor()+ 0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        preYesjRadioButton = new javax.swing.JRadioButton();
        preNojRadioButton = new javax.swing.JRadioButton();
        lifeNojRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lifeYesjRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        doctorjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diabNojRadioButton = new javax.swing.JRadioButton();
        diabYesjRadioButton = new javax.swing.JRadioButton();
        backjButton = new javax.swing.JButton();
        enrolljButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Health Record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 21, -1, -1));

        jLabel2.setText("Pre-Existing Diseases");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 70, -1, -1));

        preYesjRadioButton.setText("Yes");
        add(preYesjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 66, -1, -1));

        preNojRadioButton.setText("No");
        add(preNojRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 66, -1, -1));

        lifeNojRadioButton.setText("No");
        add(lifeNojRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 107, -1, -1));

        jLabel3.setText("Life Threatning Diseases");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 111, -1, -1));

        lifeYesjRadioButton.setText("Yes");
        add(lifeYesjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 107, -1, -1));

        jLabel4.setText("How Often do you see Doctor?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 157, -1, -1));
        add(doctorjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 154, 103, -1));

        jLabel5.setText("(Enter in days)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 157, -1, -1));

        jLabel6.setText("Diabetes");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 204, -1, -1));

        diabNojRadioButton.setText("No");
        add(diabNojRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 204, -1, -1));

        diabYesjRadioButton.setText("Yes");
        add(diabYesjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 204, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 324, -1, -1));

        enrolljButton.setText("Enroll");
        enrolljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolljButtonActionPerformed(evt);
            }
        });
        add(enrolljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 324, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void enrolljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolljButtonActionPerformed
        // TODO add your handling code here:
        
        if(doctorjTextField.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Some of the feilds are null");
            
        }
        else
        {
            preExistingCheck();
        lifeTreating();
        diabetes();
        if(Integer.parseInt(doctorjTextField.getText()) > 30)
        {
            person.setRiskFactor(person.getRiskFactor()+ 1);
        }
        
        }
        
    }//GEN-LAST:event_enrolljButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JRadioButton diabNojRadioButton;
    private javax.swing.JRadioButton diabYesjRadioButton;
    private javax.swing.JTextField doctorjTextField;
    private javax.swing.JButton enrolljButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton lifeNojRadioButton;
    private javax.swing.JRadioButton lifeYesjRadioButton;
    private javax.swing.JRadioButton preNojRadioButton;
    private javax.swing.JRadioButton preYesjRadioButton;
    // End of variables declaration//GEN-END:variables
}
