/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRegistration;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.EnterpriseDirectory;
import Business.Exchange.Exchange;
import Business.SmallBusiness.SmallBusiness;
import Business.SmallBusinessRole;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class AddSmallBusinessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddSmallBusinessJPanel
     */
    JPanel UserProcessContainer;
    Business business;
    EnterpriseDirectory enterpriseDirectory;
    public AddSmallBusinessJPanel(JPanel UserProcessContainer,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        enterpriseDirectory = business.getEnterpriseDirectory();
        exchangejComboBox.removeAllItems();
       
        for(Enterprise enterprise:enterpriseDirectory.getEnterpriseDirectory())
        {
            if(enterprise.getEnterpriseName().equals("Exchange"))
            {
                exchangejComboBox.addItem(enterprise);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        companyNamejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adrLine1jTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        zipjTextField = new javax.swing.JTextField();
        statejTextField = new javax.swing.JTextField();
        adrLine2jTextField = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exchangejComboBox = new javax.swing.JComboBox();
        userNamejTextField = new javax.swing.JTextField();
        registerjButton = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add Small Business");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 29, -1, -1));

        jLabel2.setText("Company Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 77, -1, -1));
        add(companyNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 74, 77, -1));

        jLabel8.setText("Address Line 1");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 213, -1, -1));

        jLabel9.setText("Address Line 2");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 251, -1, -1));
        add(adrLine1jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 210, 106, -1));

        jLabel12.setText("Address");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 181, -1, -1));

        jLabel11.setText("Zip");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 366, -1, -1));

        jLabel10.setText("State");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 289, -1, -1));
        add(zipjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 363, 106, -1));
        add(statejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 286, 106, -1));
        add(adrLine2jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 248, 106, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 416, -1, -1));

        jLabel14.setText("Exchange");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 158, -1, -1));

        jLabel5.setText("UserName");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 77, -1, -1));

        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 120, -1, -1));

        add(exchangejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 155, 100, -1));
        add(userNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 74, 108, -1));

        registerjButton.setText("Register");
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });
        add(registerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 416, -1, -1));
        add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 117, 108, -1));

        jLabel3.setText("City");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 328, -1, -1));
        add(cityjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 325, 106, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        // TODO add your handling code here:
        if(companyNamejTextField.getText().length() == 0 ||
            cityjTextField.getText().length() == 0 ||
            
            adrLine1jTextField.getText().length() == 0 ||
            statejTextField.getText().length() == 0||
            zipjTextField .getText().length() == 0 ||
            userNamejTextField.getText().length() == 0 ||
            jPasswordField.getText().length()== 0)
        {
            JOptionPane.showMessageDialog(null, "Some of the feilds are null");
        }
        else
        {
            try {
                
                Integer.parseInt(zipjTextField.getText());

            } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(null, "Zip  Must be a Numeric");
                return;
            }
            Exchange selectedExchange = (Exchange)exchangejComboBox.getSelectedItem();
            SmallBusinessRole smallBusinessRole = new SmallBusinessRole();
            SmallBusiness smallBusiness = selectedExchange.getSmallBusinessDirectory().newSmallBusiness();
            UserAccount userAccount = selectedExchange.getUserAccountDirectory().newUserAccount();
            
            smallBusiness.setCompanyName(companyNamejTextField.getText());
            
            smallBusiness.getAddress().setAddressLine1(adrLine1jTextField.getText());
            smallBusiness.getAddress().setAddressLine2(adrLine2jTextField.getText());
            smallBusiness.getAddress().setCity("Boston");
            smallBusiness.getAddress().setState(statejTextField.getText());
            smallBusiness.getAddress().setZip(Integer.parseInt(zipjTextField.getText()));
            userAccount.setUserName(userNamejTextField.getText());
            userAccount.setPassword(jPasswordField.getText());
            userAccount.setStatus(true);
            userAccount.setPerson(null);
            userAccount.setRole(smallBusinessRole);
            userAccount.setExchangeEnterprise(selectedExchange);
            userAccount.setSmallBusiness(smallBusiness);
            JOptionPane.showMessageDialog(null,"Company Registered");
        }
    }//GEN-LAST:event_registerjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adrLine1jTextField;
    private javax.swing.JTextField adrLine2jTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JTextField companyNamejTextField;
    private javax.swing.JComboBox exchangejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton registerjButton;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JTextField userNamejTextField;
    private javax.swing.JTextField zipjTextField;
    // End of variables declaration//GEN-END:variables
}
