/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRegistration;

import Business.Business;
import Business.Customer;
import Business.CustomerRole;
import Business.Enterprise.Enterprise;
import Business.Exchange.Exchange;
import Business.SmallBusiness.SmallBusiness;
import Business.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class CustomerRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerRegistrationJPanel
     */
    JPanel UserProcessContainer;
    Business business;
    public CustomerRegistrationJPanel(JPanel UserProcessContainer,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.business = business;
        exchangejComboBox.removeAllItems();
       
        for(Enterprise enterprise:business.getEnterpriseDirectory().getEnterpriseDirectory())
        {
            if(enterprise.getEnterpriseName().equals("Exchange"))
            {
                exchangejComboBox.addItem(enterprise);
            }
        }
        
       if(empYesjRadioButton.isSelected())
       {
           sBReftrsh();
       }
        
    }
    private void sBReftrsh()
    {
        Exchange selectedExchange = (Exchange)exchangejComboBox.getSelectedItem();
         companyjComboBox.removeAllItems();
        
        for(SmallBusiness sB:selectedExchange.getSmallBusinessDirectory().getSmallBusinessDirectory())
        {
            companyjComboBox.addItem(sB);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNamejTextField = new javax.swing.JTextField();
        lastNamejTextField = new javax.swing.JTextField();
        agejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userNamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        registerjButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        adrLine1jTextField = new javax.swing.JTextField();
        adrLine2jTextField = new javax.swing.JTextField();
        statejTextField = new javax.swing.JTextField();
        zipjTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        exchangejComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        companyjComboBox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        yesjRadioButton = new javax.swing.JRadioButton();
        nojRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        incomejTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        empYesjRadioButton = new javax.swing.JRadioButton();
        empNojRadioButton = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        ssnjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 66, -1, -1));

        jLabel2.setText("Last Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 109, -1, -1));

        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 154, -1, -1));
        add(firstNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 63, 100, -1));
        add(lastNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 106, 100, -1));
        add(agejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 151, 100, -1));

        jLabel5.setText("UserName");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 66, -1, -1));
        add(userNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 63, 100, -1));

        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 106, -1, -1));
        add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 106, 100, -1));

        registerjButton.setText("Register");
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });
        add(registerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 421, -1, -1));

        jLabel7.setText("Customer Registration");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 19, -1, -1));

        jLabel8.setText("Address Line 1");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 194, -1, -1));

        jLabel9.setText("Address Line 2");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 232, -1, -1));

        jLabel10.setText("State");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 314, -1, -1));

        jLabel11.setText("Zip");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 358, -1, -1));

        jLabel12.setText("Address");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 177, -1, -1));
        add(adrLine1jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 191, 103, -1));
        add(adrLine2jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 229, 103, -1));
        add(statejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 308, 103, -1));
        add(zipjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 355, 103, -1));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 397, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 421, -1, -1));

        jLabel14.setText("Exchange");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 154, -1, -1));

        exchangejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangejComboBoxActionPerformed(evt);
            }
        });
        add(exchangejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 151, 100, -1));

        jLabel15.setText("Company");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 298, -1, -1));

        companyjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyjComboBoxActionPerformed(evt);
            }
        });
        add(companyjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 295, 92, -1));

        jLabel16.setText("City");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 270, -1, -1));
        add(cityjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 267, 103, -1));

        jLabel17.setText("Marital Status");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 246, -1, -1));

        yesjRadioButton.setText("Yes");
        yesjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesjRadioButtonActionPerformed(evt);
            }
        });
        add(yesjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 242, -1, -1));

        nojRadioButton.setText("No");
        add(nojRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 242, -1, -1));

        jLabel4.setText("Income");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 194, -1, -1));
        add(incomejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 191, 100, -1));

        jLabel18.setText("Employee");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 358, -1, -1));

        empYesjRadioButton.setText("Yes");
        empYesjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empYesjRadioButtonActionPerformed(evt);
            }
        });
        add(empYesjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 354, -1, -1));

        empNojRadioButton.setText("No");
        add(empNojRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 354, -1, -1));

        jLabel19.setText("SSN");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 425, -1, -1));
        add(ssnjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 422, 87, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        // TODO add your handling code here:
         if(firstNamejTextField.getText().length() == 0 ||
                lastNamejTextField.getText().length() == 0 ||
                agejTextField.getText().length() == 0 ||
                adrLine1jTextField.getText().length() == 0 ||
                statejTextField.getText().length() == 0||
                zipjTextField .getText().length() == 0 ||
                 userNamejTextField.getText().length() == 0 ||
                  ssnjTextField.getText().length() == 0 ||
                 jPasswordField.getText().length()== 0 
                 || cityjTextField.getText().length() == 0
                 ||( !yesjRadioButton.isSelected()
                 && !nojRadioButton.isSelected()))
         {
             JOptionPane.showMessageDialog(null, "Some of the feilds are null");
         }
         else
         {
             try {
                   Integer.parseInt(agejTextField.getText());
                   Integer.parseInt(zipjTextField.getText());
                   Integer.parseInt(ssnjTextField.getText());
                   Double.parseDouble(incomejTextField.getText());
             
             } catch (NumberFormatException e) {
           
            JOptionPane.showMessageDialog(null, "Zip and Age Must be a Numeric");
            return;
        }
            
             Exchange selectedExchange = (Exchange)exchangejComboBox.getSelectedItem();
             for(Customer c : selectedExchange.getCustomerDirectory().getCustomerDirectory())
             {
//                 if(c.getSSN().equals())
//                 {
//                     
//                 }
             }
             
             SmallBusiness selectedSmallBusiness = (SmallBusiness)companyjComboBox.getSelectedItem();
             Customer customer = selectedExchange.getCustomerDirectory().newCustomer();
             UserAccount userAccount = selectedExchange.getUserAccountDirectory().newUserAccount();
             CustomerRole customerRole = new CustomerRole();
             customer.setFirstName(firstNamejTextField.getText());
             customer.setLastName(lastNamejTextField.getText());
             if(nojRadioButton.isSelected())
             {
                 customer.setMaritalStatus(false);
             }
             else if (yesjRadioButton.isSelected())
             {
                 customer.setMaritalStatus(true);
             }   
                 
             customer.setType("Normal");
             customer.setAge(Integer.parseInt(agejTextField.getText()));
             SimpleDateFormat formatter= new SimpleDateFormat("yyyy/MMM/dd HH:mm:ss");
             //String dob = formatter.format(jCalendar1.getDate());
            // customer.setDOB(dob);
             if(empNojRadioButton.isSelected())
             {
                 customer.setSmallBusiness( null);
                 customer.setSmallBusinessStatus(false);
                 customer.setEmployeeStatus(false);
             }
             else 
                 
             {
                 if(selectedExchange.getSmallBusinessDirectory().getSmallBusinessDirectory().isEmpty())
                 {
                     customer.setSmallBusiness(null);
                     customer.setSmallBusinessStatus(false);
                     customer.setEmployeeStatus(true);
                 }
                 else 
                 {
                 customer.setSmallBusiness( selectedSmallBusiness);
                 customer.setSmallBusinessStatus(false);
                 customer.setEmployeeStatus(true);
                 }
             }
             customer.getAddress().setAddressLine1(adrLine1jTextField.getText());
             customer.getAddress().setAddressLine2(adrLine2jTextField.getText());
             customer.getAddress().setCity("Boston");
             customer.getAddress().setState(statejTextField.getText());
             customer.getAddress().setZip(Integer.parseInt(zipjTextField.getText()));
             customer.setIncome(Double.parseDouble(incomejTextField.getText()));
             customer.setSSN(Integer.parseInt(ssnjTextField.getText()));
             
             userAccount.setUserName(userNamejTextField.getText());
             userAccount.setPassword(jPasswordField.getText());
             userAccount.setStatus(true);
             userAccount.setPerson(customer);
             userAccount.setRole(customerRole);
             userAccount.setExchangeEnterprise(selectedExchange);
             userAccount.setCustomer(customer);
             
             JOptionPane.showMessageDialog(null, "Customer Registered");
         }
    }//GEN-LAST:event_registerjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void companyjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyjComboBoxActionPerformed

    private void exchangejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exchangejComboBoxActionPerformed

    private void yesjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesjRadioButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_yesjRadioButtonActionPerformed

    private void empYesjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empYesjRadioButtonActionPerformed
        // TODO add your handling code here:
         sBReftrsh();
    }//GEN-LAST:event_empYesjRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adrLine1jTextField;
    private javax.swing.JTextField adrLine2jTextField;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JComboBox companyjComboBox;
    private javax.swing.JRadioButton empNojRadioButton;
    private javax.swing.JRadioButton empYesjRadioButton;
    private javax.swing.JComboBox exchangejComboBox;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JTextField incomejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField lastNamejTextField;
    private javax.swing.JRadioButton nojRadioButton;
    private javax.swing.JButton registerjButton;
    private javax.swing.JTextField ssnjTextField;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JTextField userNamejTextField;
    private javax.swing.JRadioButton yesjRadioButton;
    private javax.swing.JTextField zipjTextField;
    // End of variables declaration//GEN-END:variables
}
