/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRegistration;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class CustomerTypeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerTypeJPanel
     */
    JPanel UserProcessContainer;
    public CustomerTypeJPanel(JPanel UserProcessContainer) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        
        customerTypejComboBox.removeAllItems();
        
        customerTypejComboBox.addItem("Individual");
        customerTypejComboBox.addItem("Small Business");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerTypejComboBox = new javax.swing.JComboBox();
        go = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Select Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 28, -1, -1));

        jLabel2.setText("Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 112, -1, -1));

        add(customerTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 104, 96, -1));

        go.setText("Go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 103, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 278, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox customerTypejComboBox;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
