/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Treasurary;

import Business.Transaction.Transaction;
import Business.UserAccount;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ExchangeFinancialsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExchnaqgeFinancialsJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    public ExchangeFinancialsJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        DecimalFormat df = new DecimalFormat("#.##");
        revjTextField.setText(String.valueOf(df.format(userAccount.getExchangeEnterprise().getExchangeRevenue())));
        
        Refresh();
    }

    public void Refresh()
    {
        int rowCount = transjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)transjTable.getModel()).removeRow(i);
       }
                        
        for(Transaction t : userAccount.getExchangeEnterprise().getTransactionHistory().getTransactionHistory())
        {
         
            Object row[] = new Object[3];
            
            row[0] = t.getPaidDate();
            row[1] = t.getAmount();
            row[2] = t.getInsuranceEnterprise();
            
            
            
            
           
           
          
            
            DefaultTableModel defTableModel = (DefaultTableModel)transjTable.getModel();
                    defTableModel.addRow(row);
           }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        revjTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        transjTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 371, -1, -1));

        jLabel1.setText("Exchange Financials");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 19, -1, -1));

        jLabel2.setText("Total Revenue till Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 65, -1, -1));

        revjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revjTextFieldActionPerformed(evt);
            }
        });
        add(revjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 59, 88, -1));

        transjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Amount", "Insurance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 151, -1, 92));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
         UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void revjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revjTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField revjTextField;
    private javax.swing.JTable transjTable;
    // End of variables declaration//GEN-END:variables
}
