/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Treasurary;

import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ManageTreasuryEmployeesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTreasuryEmployeesJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    EmployeeDirectory employeeDirectory;
    public ManageTreasuryEmployeesJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        employeeDirectory = userAccount.getExchangeEnterprise().getTreasuryOrganization().getEmployeeDirectory();
        Refresh();
    }
     public void Refresh()
    {
          int rowCount = employeejTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)employeejTable.getModel()).removeRow(i);
       }
        
        ArrayList<Employee> eList = employeeDirectory.getEmployeeDirectory();
        
        for(Employee e : eList)
        {
                       
          
            Object row[] = new Object[3];
            
            row[0] = e.getFirstName();
            row[1] = e.getLastName();
            
            row[2] = "Accounts";
            
            
            
            DefaultTableModel defTableModel = (DefaultTableModel)employeejTable.getModel();
                    defTableModel.addRow(row);
           
            
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeejTable = new javax.swing.JTable();
        addjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Department"
            }
        ));
        jScrollPane1.setViewportView(employeejTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 110, -1, 99));

        addjButton.setText("Add");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        add(addjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 282, -1, -1));

        backjButton.setText("Back >>");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 343, -1, -1));

        jLabel1.setText("Manage Employees");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 42, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        AddTreasuryEmployeeJPanel addTreasuryEmployeeJPanel  = new AddTreasuryEmployeeJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("AddTreasury",addTreasuryEmployeeJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_addjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTable employeejTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
