/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Treasurary;

import Business.UserAccount;
import Business.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haripal
 */
public class ManageTreasuryUserAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTreasuryUserAccountsJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
     UserAccountDirectory userAccountDirectory;
    public ManageTreasuryUserAccountsJPanel(JPanel UserProcessContainer,UserAccount userAccount) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        userAccountDirectory = userAccount.getExchangeEnterprise().getTreasuryOrganization().getUserAccountDirectory();
        Refresh();
    }
    
    public void Refresh()
    {
          int rowCount = UAjTable.getRowCount();
       for(int i = rowCount - 1; i>=0; i--)
       {
           ((DefaultTableModel)UAjTable.getModel()).removeRow(i);
       }
        
        ArrayList<UserAccount> uAList = userAccountDirectory.getUserDirectory();
        
        for(UserAccount ua : uAList)
        {
                       
          
            Object row[] = new Object[4];
            
            row[0] = ua;
            row[1] = ua.getPassword();
            
            row[2] = ua.getPerson();
            
            if(ua.isStatus())
            {
            row[3] = "Enabled";
            }
            else
            {
             row[3] = "Disabled";  
            }
            
            
            DefaultTableModel defTableModel = (DefaultTableModel)UAjTable.getModel();
                    defTableModel.addRow(row);
           
            
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UAjTable = new javax.swing.JTable();
        enablejButton = new javax.swing.JButton();
        disablejButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        UAjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UserAccount", "Password", "Person", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(UAjTable);

        enablejButton.setText("Enable UserAccounts");
        enablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enablejButtonActionPerformed(evt);
            }
        });

        disablejButton.setText("Disable");
        disablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disablejButtonActionPerformed(evt);
            }
        });

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 106, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(295, 295, 295)
                            .addComponent(disablejButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(backjButton)
                            .addGap(59, 59, 59)
                            .addComponent(enablejButton)))
                    .addGap(0, 107, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(88, 88, 88)
                    .addComponent(disablejButton)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backjButton)
                        .addComponent(enablejButton))
                    .addGap(0, 59, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enablejButtonActionPerformed

        int selectedRowCount = UAjTable.getSelectedRowCount();
        if(selectedRowCount == 0)
        {
            JOptionPane.showMessageDialog(null,"Please select row");
            return;
        }
        //System.out.println("selected Row Count" + selectedRowCount);
        if(selectedRowCount <= 0 || selectedRowCount> UAjTable.getRowCount())
        {
            return;
        }
        //System.out.println("After selected Row Count");
        int selectedRow =  UAjTable.getSelectedRow();
        UserAccount selectedUA = (UserAccount)UAjTable.getValueAt(selectedRow, 0);
        selectedUA.setStatus(true);
        Refresh();
    }//GEN-LAST:event_enablejButtonActionPerformed

    private void disablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disablejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowCount = UAjTable.getSelectedRowCount();
        if(selectedRowCount == 0)
        {
            JOptionPane.showMessageDialog(null,"Please select row");
            return;
        }
        //System.out.println("selected Row Count" + selectedRowCount);
        if(selectedRowCount <= 0 || selectedRowCount> UAjTable.getRowCount())
        {
            return;
        }
        //System.out.println("After selected Row Count");
        int selectedRow =  UAjTable.getSelectedRow();
        UserAccount selectedUA = (UserAccount)UAjTable.getValueAt(selectedRow, 0);
        selectedUA.setStatus(false);
        Refresh();
    }//GEN-LAST:event_disablejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here
        UserProcessContainer.remove(this);
        CardLayout cardLayout =(CardLayout)UserProcessContainer.getLayout();
        cardLayout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UAjTable;
    private javax.swing.JButton backjButton;
    private javax.swing.JButton disablejButton;
    private javax.swing.JButton enablejButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
