/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Treasurary;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class TreasuraryEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TreasuraryEmployeeWorkAreaJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    Business business;
    public TreasuraryEmployeeWorkAreaJPanel(JPanel UserProcessContainer,UserAccount userAccount,Enterprise enterprise,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewPaymentsjButton = new javax.swing.JButton();
        accountsPayablejButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Treasurary Employee WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 27, -1, -1));

        viewPaymentsjButton.setText("Exchange Financials");
        viewPaymentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentsjButtonActionPerformed(evt);
            }
        });
        add(viewPaymentsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 88, -1, -1));

        accountsPayablejButton.setText("Accounts Payable");
        accountsPayablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsPayablejButtonActionPerformed(evt);
            }
        });
        add(accountsPayablejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 154, 129, -1));

        jButton1.setText("Manage Staff");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 88, 137, -1));

        jButton2.setText("ManageUserAccounts");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 154, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void accountsPayablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsPayablejButtonActionPerformed
        // TODO add your handling code here:
        ViewAllCustomerTransactionsJPanel  viewAllCustomerTransactionsJPanel  = new ViewAllCustomerTransactionsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("viewCustomerTransactions",viewAllCustomerTransactionsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
        
    }//GEN-LAST:event_accountsPayablejButtonActionPerformed

    private void viewPaymentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentsjButtonActionPerformed
        // TODO add your handling code here:
        ExchangeFinancialsJPanel exchangeFinancialsJPanel  = new ExchangeFinancialsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("exchangeFinancials",exchangeFinancialsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
        
    }//GEN-LAST:event_viewPaymentsjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageTreasuryEmployeesJPanel manageTreasuryEmployeesJPanel  = new ManageTreasuryEmployeesJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("manageTreasuryEmployees",manageTreasuryEmployeesJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         ManageTreasuryUserAccountsJPanel manageTreasuryUserAccountsJPanel  = new ManageTreasuryUserAccountsJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("TUserAcconts",manageTreasuryUserAccountsJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountsPayablejButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewPaymentsjButton;
    // End of variables declaration//GEN-END:variables
}
