/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SmallBusiness;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Haripal
 */
public class SmallBusinessWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SmallBusinessWorkAreaJPanel
     */
    JPanel UserProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    Business business;
    public SmallBusinessWorkAreaJPanel(JPanel UserProcessContainer,UserAccount userAccount,Enterprise enterprise,Business business) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewOffersByInsurancejButton = new javax.swing.JButton();
        approveEmployeejButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Small Business Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 27, -1, -1));

        viewOffersByInsurancejButton.setText("View Offers By Insurance");
        viewOffersByInsurancejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOffersByInsurancejButtonActionPerformed(evt);
            }
        });
        add(viewOffersByInsurancejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 70, -1, -1));

        approveEmployeejButton.setText("Approve Employee");
        approveEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveEmployeejButtonActionPerformed(evt);
            }
        });
        add(approveEmployeejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 128, 155, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewOffersByInsurancejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOffersByInsurancejButtonActionPerformed
        // TODO add your handling code here:
        ViewOffersByInsuranceJPanel viewOffersByInsuranceJPanel  = new ViewOffersByInsuranceJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("ViewYourOffersByInsurance",viewOffersByInsuranceJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_viewOffersByInsurancejButtonActionPerformed

    private void approveEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveEmployeejButtonActionPerformed
        // TODO add your handling code here:
        ApproveEmployeeJPanel approveEmployeeJPanel  = new ApproveEmployeeJPanel(UserProcessContainer,userAccount);
        UserProcessContainer.add("approveemployee",approveEmployeeJPanel);
        CardLayout cardLayout = (CardLayout)UserProcessContainer.getLayout();
        cardLayout.next(UserProcessContainer);
    }//GEN-LAST:event_approveEmployeejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveEmployeejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewOffersByInsurancejButton;
    // End of variables declaration//GEN-END:variables
}
